# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Blog Index Analyzer Local Server
"""
import os

block_cipher = None

a = Analysis(
    ['local_server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.py', '.'),
        ('main.py', '.'),
        ('routers', 'routers'),
        ('services', 'services'),
        ('schemas', 'schemas'),
        ('database', 'database'),
        ('models', 'models'),
        ('middleware', 'middleware'),
        ('utils', 'utils'),
        ('analyzer', 'analyzer'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'pydantic',
        'pydantic_settings',
        'starlette',
        'starlette.routing',
        'starlette.responses',
        'starlette.middleware',
        'starlette.middleware.cors',
        'httpx',
        'requests',
        'bs4',
        'lxml',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'email_validator',
        'passlib',
        'passlib.handlers',
        'passlib.handlers.bcrypt',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'h11',
        'httpcore',
        'sniffio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'playwright',
        'selenium',
        'tkinter',
        'anthropic',
        'pystray',
        'PIL',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BlogIndexAnalyzer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
