const fs=require('fs'),path=require('path');const {classify}=require('./_haeul_20260909_analyze');const D=path.join(__dirname,'reports','haeul_intent_20260909'),read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'))),save=(n,x)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(x));
function csv(n,a){if(!a.length)return;const cs=Object.keys(a[0]);fs.writeFileSync(path.join(D,n+'.csv'),'\ufeff'+[cs,...a.map(r=>cs.map(c=>r[c]??''))].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'));}
const full=read('search_reports_full'),gm=new Map(read('groups').map(g=>[g.nccAdgroupId,g])),cm=new Map(read('campaigns').map(c=>[c.nccCampaignId,c]));
const raw=full.searchTerms.filter(r=>r.click30>0).map(r=>({...r,...classify(r.keyword),group:gm.get(r.gid)?.name||'삭제/미조회',campaign:cm.get(r.cid)?.name||r.cid}));csv('실제검색어_클릭발생_전체_30일_그룹기기별',raw);
const map=new Map();for(const x of full.searchTerms){const r=map.get(x.keyword)||{keyword:x.keyword,...classify(x.keyword),imp30:0,click30:0,cost30:0,imp7:0,click7:0,cost7:0};for(const f of ['imp30','click30','cost30','imp7','click7','cost7'])r[f]+=x[f];map.set(x.keyword,r);}
const clicked=[...map.values()].filter(x=>x.click30>0).sort((a,b)=>b.click30-a.click30);csv('실제검색어_클릭발생_전체_30일',clicked);save('search_clicked',clicked);
const sum=a=>a.reduce((s,r)=>({clicks:s.clicks+r.click30,cost:s.cost+r.cost30,impressions:s.impressions+r.imp30}),{clicks:0,cost:0,impressions:0});const summary={period:full.period,days:full.days.length,uniqueClickedSearchTerms:clicked.length,clickedSearchRows:raw.length,search:sum(full.searchTerms),adDetail:sum(full.adKeywords),unattributedAd:sum(full.adKeywords.filter(x=>x.keywordId==='-')),tiers:{},byCampaign:[]};
for(const r of clicked){const t=summary.tiers[r.tier]||={terms:0,clicks:0,cost:0,click7:0};t.terms++;t.clicks+=r.click30;t.cost+=r.cost30;t.click7+=r.click7;}
for(const [id,c]of cm){const term=full.searchTerms.filter(r=>r.cid===id),ad=full.adKeywords.filter(r=>r.cid===id);summary.byCampaign.push({id,name:c.name,search:sum(term),ad:sum(ad),top:term.filter(r=>r.click30>0).sort((a,b)=>b.click30-a.click30).slice(0,15).map(r=>({kw:r.keyword,c:r.click30,cost:r.cost30,type:r.matchType}))});}
save('search_summary',summary);console.log('SUMMARY',JSON.stringify(summary));console.log('SEARCH TOP',JSON.stringify(clicked.slice(0,100)));console.log('SEVERE',JSON.stringify(clicked.filter(x=>x.priority>=3).slice(0,80)));
