const fs=require('fs'),path=require('path'),assert=require('assert');const D=path.join(__dirname,'reports','haeul_intent_20260909'),CID=3442423,read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'))),save=(n,x)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(x));
const state={startedAt:new Date().toISOString(),events:[],complete:false};
async function call(method,p,body=null){const r=await fetch('https://blog-index-analyzer.fly.dev/api/naver-ad/keyword-pool/debug/naver-raw?user_id=1&customer_id='+CID,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({method,path:p,body,customer_id:String(CID)}),signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok||!d.success)throw Error('API '+r.status+' '+p.split('?')[0]+' '+String(d.error||'').slice(0,200));return d.response;}
(async()=>{const plan=read('change_plan');assert.equal(plan.customerId,CID);const campaigns=await call('GET','/ncc/campaigns');save('apply_before_campaigns',campaigns);const cm=new Map(campaigns.map(c=>[c.nccCampaignId,c]));for(const p of plan.campaignBudgets){const c=cm.get(p.id);assert(c&&c.customerId===CID&&!c.userLock);assert.equal(c.dailyBudget,p.before);assert(!c.sharedBudgetId);}
 const gids=[...new Set([...plan.keywords.map(k=>k.gid),...plan.groupBudgets.map(g=>g.id)])],groups=[],inventory=[];
 for(const gid of gids){const g=await call('GET','/ncc/adgroups/'+gid);assert.equal(g.customerId,CID);groups.push(g);const keywords=await call('GET','/ncc/keywords?nccAdgroupId='+gid);assert(Array.isArray(keywords));inventory.push({gid,keywords});}
 save('apply_before_groups',groups);save('apply_before_inventory',inventory);const gm=new Map(groups.map(g=>[g.nccAdgroupId,g])),km=new Map(inventory.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));
 for(const p of plan.keywords){const k=km.get(p.id);assert(k&&!k.userLock&&!gm.get(p.gid).userLock);assert.equal(k.bidAmt,p.oldBid);assert.equal(k.useGroupBidAmt,p.oldGroup);assert(p.after>p.before&&p.after<=10000);}
 for(const p of plan.groupBudgets)assert.equal(gm.get(p.id).dailyBudget,p.before);
 save('apply_state',state);
 for(let i=0;i<plan.keywords.length;i+=50){const part=plan.keywords.slice(i,i+50);const r=await call('PUT','/ncc/keywords?fields=bidAmt',part.map(p=>({nccKeywordId:p.id,nccAdgroupId:p.gid,bidAmt:p.after,useGroupBidAmt:false})));assert(Array.isArray(r)&&r.length===part.length);for(const p of part){const k=r.find(x=>x.nccKeywordId===p.id);assert(k&&k.bidAmt===p.after&&!k.useGroupBidAmt);}state.events.push({type:'keyword_bids',ids:part.map(p=>p.id)});save('apply_state',state);console.log('BIDS',i+part.length);}
 for(const p of plan.groupBudgets){const g=gm.get(p.id);await call('PUT','/ncc/adgroups/'+p.id+'?fields=budget',{...g,useDailyBudget:true,dailyBudget:p.after});const after=await call('GET','/ncc/adgroups/'+p.id);assert.equal(after.dailyBudget,p.after);assert(after.useDailyBudget);state.events.push({type:'group_budget',...p});save('apply_state',state);}
 for(const p of plan.campaignBudgets){const c=cm.get(p.id);await call('PUT','/ncc/campaigns/'+p.id+'?fields=budget',{...c,useDailyBudget:true,dailyBudget:p.after});const after=await call('GET','/ncc/campaigns/'+p.id);assert.equal(after.dailyBudget,p.after);assert(after.useDailyBudget);state.events.push({type:'campaign_budget',...p});save('apply_state',state);console.log('BUDGET',p.name,p.after);}
 const afterInv=[];for(const gid of gids)afterInv.push({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)});save('apply_after_inventory',afterInv);const am=new Map(afterInv.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));for(const p of plan.keywords){const k=am.get(p.id);assert(k&&k.bidAmt===p.after&&k.useGroupBidAmt===false);assert.equal(k.userLock,km.get(p.id).userLock);}
 const ac=await call('GET','/ncc/campaigns');save('apply_after_campaigns',ac);for(const c of campaigns){const want=plan.campaignBudgets.find(p=>p.id===c.nccCampaignId)?.after??c.dailyBudget;assert.equal(ac.find(x=>x.nccCampaignId===c.nccCampaignId).dailyBudget,want);}
 state.complete=true;state.verifiedKeywords=plan.keywords.length;state.verifiedCampaigns=plan.campaignBudgets.length;state.verifiedGroups=plan.groupBudgets.length;state.completedAt=new Date().toISOString();save('apply_state',state);console.log('VERIFIED',JSON.stringify(state));
})().catch(e=>{state.error=String(e);save('apply_state',state);console.error(String(e));process.exitCode=1;});
