const fs=require('fs'),path=require('path'),assert=require('assert');
const {req,pool}=require('./_sojam_naver');
const CID=3442423,D=path.join(__dirname,'reports','haeul_intent_20260909');fs.mkdirSync(D,{recursive:true});
const save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
const get=async p=>{for(let t=0;t<4;t++){try{const r=await fetch('https://blog-index-analyzer.fly.dev/api/naver-ad/keyword-pool/debug/naver-raw?user_id=1&customer_id='+CID,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:p,method:'GET',body:null,customer_id:String(CID)}),signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok||!d.success)throw Error('Read failed HTTP '+r.status+' success='+d.success);return d.response;}catch(e){if(t===3)throw Error('Read failed '+p.split('?')[0]+' '+e.name);await new Promise(r=>setTimeout(r,2000*(t+1)));}}};
const chunks=(a,n)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
async function stats(ids,since,until){const r=await pool(chunks(ids,50),5,c=>get('/stats?ids='+encodeURIComponent(c.join(','))+'&fields='+encodeURIComponent(JSON.stringify(['impCnt','clkCnt','salesAmt','avgRnk','ccnt']))+'&timeRange='+encodeURIComponent(JSON.stringify({since,until}))));assert(r.every(x=>Array.isArray(x.data)),JSON.stringify(r.filter(x=>!Array.isArray(x.data))).slice(0,500));return r.flatMap(x=>x.data);}
(async()=>{
 const read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8'));
 const campaigns=fs.existsSync(path.join(D,'campaigns.json'))?read('campaigns'):await get('/ncc/campaigns');assert(Array.isArray(campaigns));save('campaigns',campaigns);console.log('CAMPAIGNS',campaigns.length);
 if(process.argv.includes('--probe'))return;
 const gr=fs.existsSync(path.join(D,'groups.json'))?[read('groups')]:await pool(campaigns,5,c=>get('/ncc/adgroups?nccCampaignId='+c.nccCampaignId));assert(gr.every(Array.isArray));const allGroups=gr.flat();console.log('GROUPS',allGroups.length);
 for(const [n,since,until]of [['month','2026-08-10','2026-09-08'],['week','2026-09-02','2026-09-08'],['today','2026-09-09','2026-09-09']]){if(!fs.existsSync(path.join(D,'campaign_'+n+'.json')))save('campaign_'+n,await stats(campaigns.map(c=>c.nccCampaignId),since,until));if(!fs.existsSync(path.join(D,'group_'+n+'.json')))save('group_'+n,await stats(allGroups.map(g=>g.nccAdgroupId),since,until));}
 const clicked=new Set(read('group_month').filter(x=>x.clkCnt>0).map(x=>x.id));const groups=allGroups.filter(g=>g.adgroupType==='WEB_SITE'&&(clicked.has(g.nccAdgroupId)||/두통|머리아|머리통증|삼차신경통|후두신경통|실수요/.test(g.name)));save('scope_groups',groups);console.log('CLICK AND CORE GROUPS',groups.length);
 const file=path.join(D,'inventory.jsonl'),cache=new Map(fs.existsSync(file)?fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map(l=>{const x=JSON.parse(l);return [x.gid,x]}):[]);let count=0;
 const rr=await pool(groups.filter(g=>!cache.has(g.nccAdgroupId)),6,async g=>{const keywords=await get('/ncc/keywords?nccAdgroupId='+g.nccAdgroupId);assert(Array.isArray(keywords));const x={gid:g.nccAdgroupId,keywords,at:new Date().toISOString()};fs.appendFileSync(file,JSON.stringify(x)+'\n');cache.set(x.gid,x);if(++count%200===0)console.log('inventory',cache.size,'/',groups.length);return true;});assert(rr.every(x=>x===true));const inv=groups.map(g=>cache.get(g.nccAdgroupId));save('inventory',inv);
 const ids=inv.flatMap(x=>x.keywords.map(k=>k.nccKeywordId));console.log('KEYWORDS',ids.length);
 for(const [n,since,until]of [['month','2026-08-10','2026-09-08'],['week','2026-09-02','2026-09-08']]){const dir=path.join(D,'stats_'+n);fs.mkdirSync(dir,{recursive:true});const parts=chunks(ids,50);let done=0;const rr=await pool(parts,6,async(c,i)=>{const f=path.join(dir,i+'.json');if(fs.existsSync(f))return JSON.parse(fs.readFileSync(f));const r=await stats(c,since,until);fs.writeFileSync(f,JSON.stringify(r));if(++done%100===0)console.log('stats',n,done,'/',parts.length);return r;});assert(rr.every(Array.isArray));save('keyword_'+n,rr.flat());console.log('STATS',n,'complete');}
 save('shared_budgets',await get('/ncc/shared-budgets'));
 const active=groups.filter(g=>!g.userLock&&campaigns.some(c=>c.nccCampaignId===g.nccCampaignId&&!c.userLock));const ads=await pool(active,5,async g=>({gid:g.nccAdgroupId,ads:await get('/ncc/ads?nccAdgroupId='+g.nccAdgroupId)}));save('ads',ads);
 save('meta',{customerId:CID,completedAt:new Date().toISOString(),campaigns:campaigns.length,groups:groups.length,keywords:ids.length});console.log('DONE');
})().catch(e=>{console.error(String(e));process.exitCode=1;});
