const fs=require('fs'),path=require('path'),assert=require('assert');const {req,pool,sleep}=require('./_sojam_naver');const D=path.join(__dirname,'reports/kiness_delivery_boost_20260909'),read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
const call=async(m,p,b)=>{for(let i=0;i<4;i++){try{const r=await req(m,p,b,441986,m==='PUT'||m==='POST'?1:4);if(r===undefined)throw Error('Missing response '+p);return r;}catch(e){if(i===3||!String(e).includes('409'))throw e;await sleep(3000);}}};
(async()=>{
 const rows=read('plan'),gids=[...new Set(rows.map(r=>r.gid))],camps=await call('GET','/ncc/campaigns'),cm=new Map(camps.map(c=>[c.nccCampaignId,c]));const budgets=await call('GET','/ncc/shared-budgets');save('budgets_preflight',budgets);const total=budgets.find(b=>b.sharedBudgetId==='nsb-a001-01-000000000073065');assert(total?.dailyBudget===178000&&total.deliveryMethod==='ACCELERATED');assert(camps.filter(c=>c.campaignTp==='WEB_SITE').every(c=>c.sharedBudgetId===total.sharedBudgetId));
 assert.equal(camps.filter(c=>!c.userLock&&!['WEB_SITE','BRAND_SEARCH'].includes(c.campaignTp)).reduce((s,c)=>s+(c.useDailyBudget?c.dailyBudget:Infinity),0),2000);
 const groups=await pool(gids,6,gid=>call('GET','/ncc/adgroups/'+gid));assert(groups.every(g=>g?.nccAdgroupId));save('groups_preflight',groups);const gm=new Map(groups.map(g=>[g.nccAdgroupId,g]));for(const r of rows){const g=gm.get(r.gid);assert(!g.userLock&&!cm.get(r.cid).userLock);assert.equal(g.pcNetworkBidWeight??100,r.pcWeight);assert.equal(g.mobileNetworkBidWeight??100,r.mobileWeight);}
 const inv=await pool(gids,6,async gid=>({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)}));assert(inv.every(x=>Array.isArray(x.keywords)));save('preflight_inventory',inv);const km=new Map(inv.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));for(const r of rows){const k=km.get(r.id);assert(k&&!k.userLock&&k.bidAmt===r.oldBid&&k.useGroupBidAmt===r.oldGroupBid,'Concurrent change '+r.id);}
 const budgetEvents=[];
 for(const id of ['nsb-a001-02-000000000073066','nsb-a001-02-000000000073067']){const b=budgets.find(x=>x.sharedBudgetId===id);assert(b);const r=await call('PUT','/ncc/shared-budgets/'+id,{sharedBudgetId:id,customerId:441986,name:b.name,ownerType:'ADGROUP',dailyBudget:178000,deliveryMethod:'ACCELERATED'});budgetEvents.push({id,before:b.dailyBudget,after:r.dailyBudget});save('budget_events',budgetEvents);}
 const low=read('groups_before').filter(g=>!g.userLock&&!cm.get(g.nccCampaignId).userLock&&g.adgroupType==='WEB_SITE'&&!gm.has(g.nccAdgroupId));
 const liveLow=await pool(low,5,g=>call('GET','/ncc/adgroups/'+g.nccAdgroupId));assert(liveLow.every(g=>g?.nccAdgroupId));
 let info=(await call('GET','/ncc/shared-budgets')).find(b=>b.name==='키네스_정보탐색_5000_0909');if(!info&&liveLow.length){const seed=liveLow.find(g=>!g.sharedBudgetId)||liveLow[0];if(seed.sharedBudgetId)await call('PUT','/ncc/shared-budgets/adgroups?ids='+seed.nccAdgroupId);info=await call('POST','/ncc/shared-budgets',{customerId:441986,name:'키네스_정보탐색_5000_0909',ownerType:'ADGROUP',dailyBudget:5000,adgroupList:[{...seed,sharedBudgetId:null}]});seed.sharedBudgetId=info.sharedBudgetId;}
 const pending=info?liveLow.filter(g=>g.sharedBudgetId!==info.sharedBudgetId):[];for(let i=0;i<pending.length;i+=20){const chunk=pending.slice(i,i+20),attached=chunk.filter(g=>g.sharedBudgetId);if(attached.length)await call('PUT','/ncc/shared-budgets/adgroups?ids='+encodeURIComponent(attached.map(g=>g.nccAdgroupId).join(',')));await call('PUT','/ncc/adgroups?fields=sharedBudget',chunk.map(g=>({...g,sharedBudgetId:info.sharedBudgetId,sharedDailyBudget:5000,sharedBudgetName:info.name})));}
 save('information_budget_groups',low.map(g=>({gid:g.nccAdgroupId,name:g.name,cid:g.nccCampaignId,oldShared:g.sharedBudgetId,newShared:info?.sharedBudgetId})));
 const changes=rows.filter(r=>r.change),state={startedAt:new Date().toISOString(),targets:rows.length,changes:changes.length,applied:0};save('apply_state',state);
 for(let i=0;i<changes.length;i+=100){const chunk=changes.slice(i,i+100),r=await call('PUT','/ncc/keywords?fields=bidAmt',chunk.map(x=>({nccKeywordId:x.id,nccAdgroupId:x.gid,bidAmt:x.bid,useGroupBidAmt:false})));assert(Array.isArray(r)&&r.length===chunk.length);const rm=new Map(r.map(k=>[k.nccKeywordId,k]));for(const x of chunk)assert(rm.get(x.id)?.bidAmt===x.bid&&rm.get(x.id)?.useGroupBidAmt===false);state.applied+=chunk.length;save('apply_state',state);if(i%2000===0)console.log('applied',state.applied,'/',changes.length);}
 const after=await pool(gids,6,async gid=>({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)}));assert(after.every(x=>Array.isArray(x.keywords)));save('inventory_after',after);const am=new Map(after.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));for(const r of rows){const k=am.get(r.id);assert(k&&!k.userLock&&k.bidAmt===r.bid&&!k.useGroupBidAmt,'Bid verification '+r.id);}
 const ba=await call('GET','/ncc/shared-budgets');save('budgets_after',ba);assert.equal(ba.find(x=>x.sharedBudgetId===total.sharedBudgetId)?.dailyBudget,178000);for(const e of budgetEvents)assert.equal(ba.find(x=>x.sharedBudgetId===e.id)?.dailyBudget,178000);
 if(info){const attached=await call('GET','/ncc/adgroups/shared-budgets/'+info.sharedBudgetId);save('information_budget_verified',attached);const ids=new Set(attached.map(g=>g.nccAdgroupId));assert(low.every(g=>ids.has(g.nccAdgroupId)));assert.equal(ba.find(x=>x.sharedBudgetId===info.sharedBudgetId)?.dailyBudget,5000);}
 state.completedAt=new Date().toISOString();state.verified=rows.length;state.budgetConfigured=180000;state.lowIntentGroups=low.length;state.placementAndSpendGoalVerified=false;save('apply_state',state);console.log(JSON.stringify(state));
})().catch(e=>{save('apply_error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
