const fs=require('fs'),path=require('path');const {req,pool}=require('./_sojam_naver');const D=path.join(__dirname,'reports','kiness_20260914');
const read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v,null,1));
const call=async(m,p,b)=>{const r=await req(m,p,b,441986,m==='GET'?4:1);if(r===undefined)throw Error('No response '+p);return r;};
(async()=>{
if(process.argv.includes('--verify-only')){const state=read('applied'),ids=[...new Set([...state.bids,...state.created].map(x=>x.gid))];const a=await pool(ids,3,async gid=>({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)}));if(a.some(x=>!Array.isArray(x.keywords)))throw Error('Incomplete verification');save('latest_verified_keywords',a);const km=new Map(a.flatMap(x=>x.keywords).map(x=>[x.nccKeywordId,x])),failures=[];for(const x of state.bids){const k=km.get(x.id);if(!k||k.bidAmt!==x.to||k.userLock||k.useGroupBidAmt)failures.push(x.keyword);}for(const x of state.created){const k=km.get(x.id);if(!k||k.bidAmt!==x.bid||k.userLock)failures.push(x.keyword);x.status=k?.status;x.inspectStatus=k?.inspectStatus;}const budgets=await call('GET','/ncc/shared-budgets');save('latest_verified_budgets',budgets);const daily=budgets.find(x=>x.sharedBudgetId==='nsb-a001-01-000000000073065')?.dailyBudget;if(daily!==200000)failures.push('Daily budget changed');const result={at:new Date().toISOString(),bidChanges:state.bids.length,created:state.created.length,failures,newKeywordStatuses:state.created.map(x=>({keyword:x.keyword,status:x.status,inspect:x.inspectStatus})),dailySearchBudget:daily};save('verification',result);save('applied',state);console.log(JSON.stringify(result));return;}
const plan=read('remediation_plan');const state=fs.existsSync(path.join(D,'applied.json'))?read('applied'):{startedAt:new Date().toISOString(),bids:[],created:[],errors:[]};
try{const budgets=await call('GET','/ncc/shared-budgets');save('apply_budget_before',budgets);const total=budgets.find(b=>b.sharedBudgetId==='nsb-a001-01-000000000073065');if(total?.dailyBudget!==200000)throw Error('Daily budget changed, re-evaluation required');
const gids=[...new Set([...plan.changes,...plan.creates].map(x=>x.gid))];const snapshot=await pool(gids,3,async gid=>({gid,group:await call('GET','/ncc/adgroups/'+gid),keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid),ads:await call('GET','/ncc/ads?nccAdgroupId='+gid)}));save('apply_backup',snapshot);if(snapshot.some(x=>!Array.isArray(x.keywords)||!Array.isArray(x.ads)))throw Error('Incomplete preflight '+JSON.stringify(snapshot.filter(x=>x.__err)));const gm=new Map(snapshot.map(x=>[x.gid,x]));
for(const x of plan.changes){if(state.bids.some(b=>b.id===x.id))continue;const s=gm.get(x.gid),k=s.keywords.find(k=>k.nccKeywordId===x.id);if(!k||k.userLock||k.status!=='ELIGIBLE'||s.group.status!=='ELIGIBLE'||s.group.userLock)throw Error('Changed eligibility '+x.keyword);const from=k.useGroupBidAmt?s.group.bidAmt:k.bidAmt;if(from!==x.bid)throw Error('Concurrent bid change '+x.keyword+' '+from);if(x.to<x.bid||x.to>70000||x.to%10)throw Error('Invalid bid');}
for(const x of plan.creates){const s=gm.get(x.gid);if(s.group.status!=='ELIGIBLE'||s.group.userLock||!s.ads.some(a=>!a.userLock&&a.status==='ELIGIBLE'))throw Error('No serving destination '+x.keyword);if(!s.keywords.some(k=>k.keyword===x.counterpart&&k.status==='ELIGIBLE'&&!k.userLock))throw Error('Counterpart unavailable');}
save('applied',state);
const pending=plan.changes.filter(x=>!state.bids.some(b=>b.id===x.id));if(pending.length){const response=await call('PUT','/ncc/keywords?fields=bidAmt',pending.map(x=>({nccKeywordId:x.id,nccAdgroupId:x.gid,bidAmt:x.to,useGroupBidAmt:false})));save('apply_bid_response',response);if(!Array.isArray(response)||response.length!==pending.length)throw Error('Unexpected bid result');for(const x of pending){const k=response.find(k=>k.nccKeywordId===x.id);if(!k||k.bidAmt!==x.to||k.useGroupBidAmt)throw Error('Bid failed '+x.keyword);state.bids.push({id:x.id,gid:x.gid,keyword:x.keyword,from:x.bid,to:x.to,reason:x.actionReason,at:new Date().toISOString()});}save('applied',state);}
for(const gid of new Set(plan.creates.map(x=>x.gid))){const current=await call('GET','/ncc/keywords?nccAdgroupId='+gid);const missing=plan.creates.filter(x=>x.gid===gid&&!current.some(k=>k.keyword===x.keyword));if(!missing.length)continue;const response=await call('POST','/ncc/keywords?nccAdgroupId='+gid,missing.map(x=>({keyword:x.keyword,bidAmt:x.bid,useGroupBidAmt:false,userLock:false})));save('apply_create_response_'+gid,response);if(!Array.isArray(response)||response.length!==missing.length||response.some(x=>!x.nccKeywordId||x.code||x.error))throw Error('Creation failed '+gid);for(const k of response)state.created.push({id:k.nccKeywordId,gid,keyword:k.keyword,bid:k.bidAmt,status:k.status,inspectStatus:k.inspectStatus});save('applied',state);}
const after=await pool(gids,4,async gid=>({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)}));if(after.some(x=>!Array.isArray(x.keywords)))throw Error('Verification incomplete');save('apply_after',after);const km=new Map(after.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));const failures=[];for(const x of state.bids){const k=km.get(x.id);if(!k||k.bidAmt!==x.to||k.userLock||k.useGroupBidAmt)failures.push(x.keyword);}for(const x of state.created){const k=km.get(x.id);if(!k||k.bidAmt!==x.bid||k.userLock)failures.push(x.keyword);x.status=k?.status;x.inspectStatus=k?.inspectStatus;}
const endBudgets=await call('GET','/ncc/shared-budgets');save('apply_budget_after',endBudgets);if(endBudgets.find(b=>b.sharedBudgetId===total.sharedBudgetId)?.dailyBudget!==200000)failures.push('검색 일예산 변경');const verification={at:new Date().toISOString(),bidChanges:state.bids.length,created:state.created.length,failures,newKeywordStatuses:state.created.map(x=>({keyword:x.keyword,status:x.status,inspect:x.inspectStatus})),dailySearchBudget:200000};save('verification',verification);state.completedAt=new Date().toISOString();save('applied',state);console.log(JSON.stringify(verification));if(failures.length)throw Error('Verification failures');
}catch(e){state.errors.push({at:new Date().toISOString(),error:String(e)});save('applied',state);throw e;}})().catch(e=>{console.error(e);process.exitCode=1;});
