const fs=require('fs'),path=require('path'),assert=require('assert');const {req,pool,sleep}=require('./_sojam_naver');
const D=path.join(__dirname,'reports','kiness_click_rank_20260909');fs.mkdirSync(D,{recursive:true});const save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
const call=async(m,p,b)=>{const r=await req(m,p,b,441986,5);if(r===undefined)throw Error('No response '+p.split('?')[0]);return r;};
const chunks=(a,n)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
async function stats(ids,day,device=false){const rr=await pool(chunks(ids,50),5,c=>call('GET','/stats?ids='+encodeURIComponent(c.join(','))+'&fields='+encodeURIComponent(JSON.stringify(['impCnt','clkCnt','salesAmt','avgRnk','pcNxAvgRnk','mblNxAvgRnk','recentAvgRnk']))+'&timeRange='+encodeURIComponent(JSON.stringify({since:day,until:day}))+(device?'&breakdown=pcMblTp':'')));if(rr.some(x=>!Array.isArray(x.data)))throw Error('Stats invalid');return {data:rr.flatMap(x=>x.data),cycleBaseTimes:[...new Set(rr.map(x=>x.cycleBaseTm))],compTimes:[...new Set(rr.map(x=>x.compTm))]};}
(async()=>{
 const campaigns=await call('GET','/ncc/campaigns');save('campaigns',campaigns);const gr=await pool(campaigns,5,c=>call('GET','/ncc/adgroups?nccCampaignId='+c.nccCampaignId));assert(gr.every(Array.isArray));const groups=gr.flat();save('groups',groups);
 const meta={startedAt:new Date().toISOString(),yesterday:'2026-09-08',today:'2026-09-09',customerId:441986,groups:groups.length};save('meta',meta);
 const cs=await stats(campaigns.map(x=>x.nccCampaignId),meta.yesterday);save('campaign_yesterday',cs);console.log('YESTERDAY',JSON.stringify({cost:cs.data.reduce((s,x)=>s+x.salesAmt,0),clicks:cs.data.reduce((s,x)=>s+x.clkCnt,0)}));
 const gs=await stats(groups.map(x=>x.nccAdgroupId),meta.yesterday);save('group_yesterday',gs);
 const file=path.join(D,'inventory.jsonl'),cache=new Map(fs.existsSync(file)?fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map(l=>{const x=JSON.parse(l);return [x.gid,x]}):[]);let count=0;
 const rr=await pool(groups.filter(g=>!cache.has(g.nccAdgroupId)),6,async g=>{const k=await call('GET','/ncc/keywords?nccAdgroupId='+g.nccAdgroupId);assert(Array.isArray(k));const r={gid:g.nccAdgroupId,keywords:k,at:new Date().toISOString()};cache.set(r.gid,r);fs.appendFileSync(file,JSON.stringify(r)+'\n');if(++count%500===0)console.log('inventory',cache.size);return true;});assert(rr.every(x=>x===true));const inventory=groups.map(g=>cache.get(g.nccAdgroupId));save('inventory',inventory);
 const clickGroups=new Set(gs.data.filter(x=>x.clkCnt>0).map(x=>x.id)),clickedGroupIds=inventory.filter(x=>clickGroups.has(x.gid)).flatMap(x=>x.keywords.map(k=>k.nccKeywordId));save('clicked_group_keywords_yesterday',await stats(clickedGroupIds,meta.yesterday,true));console.log('click-source IDs queried',clickedGroupIds.length);
 const {evaluate}=require('./_kiness_review_rubric');const prior=JSON.parse(fs.readFileSync(path.join(__dirname,'reports','kiness_bids_20260909','plan.json')));const oldProtected=new Set(prior.filter(x=>x.protected5).map(x=>x.id));const gm=new Map(groups.map(g=>[g.nccAdgroupId,g])),cm=new Map(campaigns.map(c=>[c.nccCampaignId,c]));const evaluation=new Map(JSON.parse(fs.readFileSync(path.join(__dirname,'reports','kiness_review_20260908','evaluation_unique.json'))).map(x=>[x.keyword,x]));const targets=[];
 for(const item of inventory){const g=gm.get(item.gid),c=cm.get(g.nccCampaignId);for(const k of item.keywords){if(g.adgroupType!=='WEB_SITE')continue;const e=evaluation.get(k.keyword)||evaluate(k.keyword);if(!e.pc5_protected&&!oldProtected.has(k.nccKeywordId))continue;targets.push({id:k.nccKeywordId,keyword:k.keyword,gid:g.nccAdgroupId,cid:c.nccCampaignId,group:g.name,campaign:c.name,enabled:!k.userLock&&!g.userLock&&!c.userLock,keywordStatus:k.status,groupStatus:g.status,campaignStatus:c.status,region:e.region,geo:e.geo_zone,branch:e.branch,bid:k.useGroupBidAmt?g.bidAmt:k.bidAmt,pcWeight:g.pcNetworkBidWeight,pcEffective:Math.round((k.useGroupBidAmt?g.bidAmt:k.bidAmt)*g.pcNetworkBidWeight/100)});}}
 save('rank_targets',targets);save('rank_yesterday',await stats(targets.map(x=>x.id),meta.yesterday,true));save('rank_today',await stats(targets.map(x=>x.id),meta.today,true));meta.completedAt=new Date().toISOString();meta.instances=inventory.reduce((s,x)=>s+x.keywords.length,0);meta.rankTargets=targets.length;save('meta',meta);console.log('AUDIT COLLECTED',JSON.stringify(meta));
})().catch(e=>{save('error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
