const fs=require('fs'),path=require('path'),assert=require('assert');const {req,pool}=require('./_sojam_naver');const {calculate}=require('./_kiness_mobile_bid_policy');
const D=path.join(__dirname,'reports/kiness_mobile_budget_20260909'),read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
const call=async(m,p,b)=>{const r=await req(m,p,b,441986,m==='PUT'?1:4);if(r===undefined)throw Error('Missing response');return r;};
(async()=>{
 assert(read('collect_done').at);const targets=JSON.parse(fs.readFileSync(path.join(__dirname,'reports/kiness_click_rank_20260909/rank_targets.json'),'utf8')),inventory=read('inventory_before'),km=new Map(inventory.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));
 const gids=[...new Set(targets.map(x=>x.gid))],groups=await pool(gids,5,g=>call('GET','/ncc/adgroups/'+g));assert(groups.every(g=>g?.nccAdgroupId));save('groups_apply_before',groups);const gm=new Map(groups.map(g=>[g.nccAdgroupId,g]));const camps=await call('GET','/ncc/campaigns'),cm=new Map(camps.map(c=>[c.nccCampaignId,c]));
 const est=read('estimates'),pc=new Map(est.filter(x=>x.device==='PC').flatMap(x=>x.data).map(x=>[x.nccKeywordId,x.bid])),mo=new Map(est.filter(x=>x.device==='MOBILE').flatMap(x=>x.data).map(x=>[x.nccKeywordId,x.bid]));
 const rows=targets.map(t=>{const k=km.get(t.id),g=gm.get(t.gid),c=cm.get(t.cid);assert(k&&g&&c);const pw=g.pcNetworkBidWeight??100,mw=g.mobileNetworkBidWeight??100;return {...t,oldBid:k.bidAmt,oldGroupBid:k.useGroupBidAmt,oldBase:k.useGroupBidAmt?g.bidAmt:k.bidAmt,oldLock:k.userLock,enabled:!k.userLock&&!g.userLock&&!c.userLock,pcWeight:pw,mobileWeight:mw,pc5:pc.get(t.id),mobile5:mo.get(t.id),...calculate(pc.get(t.id),mo.get(t.id),pw,mw)};});
 save('mobile_plan',rows);assert(!rows.some(r=>r.capped),'Bid ceiling prevents requested estimate');
 const current=await pool(gids,5,async gid=>({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)}));assert(current.every(x=>Array.isArray(x.keywords)));save('preflight_inventory',current);const live=new Map(current.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));
 for(const r of rows){const k=live.get(r.id);assert(k&&k.userLock===r.oldLock);r.oldBid=k.bidAmt;r.oldGroupBid=k.useGroupBidAmt;r.oldBase=k.useGroupBidAmt?gm.get(r.gid).bidAmt:k.bidAmt;r.change=k.bidAmt!==r.bid||k.useGroupBidAmt;}save('mobile_plan',rows);
 const changes=rows.filter(r=>r.change).sort((a,b)=>(a.bid-a.oldBase)-(b.bid-b.oldBase)),state={startedAt:new Date().toISOString(),applied:0,changes:changes.length};save('mobile_apply_state',state);
 for(let i=0;i<changes.length;i+=100){const chunk=changes.slice(i,i+100),r=await call('PUT','/ncc/keywords?fields=bidAmt',chunk.map(x=>({nccKeywordId:x.id,nccAdgroupId:x.gid,bidAmt:x.bid,useGroupBidAmt:false})));assert(Array.isArray(r)&&r.length===chunk.length);const rm=new Map(r.map(x=>[x.nccKeywordId,x]));for(const x of chunk)assert(rm.get(x.id)?.bidAmt===x.bid&&rm.get(x.id)?.useGroupBidAmt===false);state.applied+=chunk.length;save('mobile_apply_state',state);if(i%500===0)console.log('applied',state.applied,'/',changes.length);}
 const after=await pool(gids,5,async gid=>({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)}));assert(after.every(x=>Array.isArray(x.keywords)));save('inventory_after',after);const am=new Map(after.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));for(const r of rows){const k=am.get(r.id);assert(k&&k.bidAmt===r.bid&&!k.useGroupBidAmt&&k.userLock===r.oldLock,'Verification '+r.id);}
 const enabled=rows.filter(r=>r.enabled);fs.writeFileSync(path.join(__dirname,'_kiness_pc5_targets.json'),JSON.stringify(enabled.map(r=>({kw:r.keyword,id:r.id,gid:r.gid}))));
 state.completedAt=new Date().toISOString();state.verified=rows.length;state.enabled=enabled.length;state.enabledUnique=new Set(enabled.map(r=>r.keyword)).size;state.mobileIncreases=rows.filter(r=>r.bid>r.oldBase).length;state.mobileDecreases=rows.filter(r=>r.bid<r.oldBase).length;state.actualPlacementVerified=false;save('mobile_apply_state',state);console.log(JSON.stringify(state));
})().catch(e=>{save('mobile_error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
