const fs=require('fs'),path=require('path'),assert=require('assert');const {req,pool}=require('./_sojam_naver');const {evaluate}=require('./_kiness_review_rubric');const {policy,calculate}=require('./_kiness_20260909_policy');const {classify}=require('./_kiness_20260908_discover');
const D=path.join(__dirname,'reports','kiness_bids_20260909'),read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
(async()=>{
 const meta=read('meta');assert(meta.completedAt);const groups=read('groups'),campaigns=read('campaigns'),npc=read('inventory_nonweb').filter(x=>x.type==='INFORMATION'),inventory=[...read('inventory'),...npc],gm=new Map(groups.map(g=>[g.nccAdgroupId,g])),cm=new Map(campaigns.map(c=>[c.nccCampaignId,c]));
 const oldPlan=JSON.parse(fs.readFileSync('_kiness_20260908_plan.json','utf8')),verified=JSON.parse(fs.readFileSync('_kiness_20260908_verified.json','utf8'));const legacy=new Set(Object.entries(oldPlan.owners).filter(([kw])=>classify(kw).tier==='region_clinic').map(([,x])=>x.id));verified.created.filter(x=>x.tier==='region_clinic').forEach(x=>legacy.add(x.id));
 const cache=new Map(JSON.parse(fs.readFileSync(path.join(__dirname,'reports','kiness_review_20260908','evaluation_unique.json'),'utf8')).map(e=>[e.keyword,e]));const rows=[];
 for(const item of inventory){const g=gm.get(item.gid),c=cm.get(g.nccCampaignId);for(const k of item.keywords){const e=cache.get(k.keyword)||evaluate(k.keyword),p=g.adgroupType==='INFORMATION'?{tier:'N_파워콘텐츠',urgency:['A','B','C'].includes(e.category)?'서비스 비교·탐색':'정보 탐색',floor:70,cap:['A','B','C'].includes(e.category)?500:e.category==='D'?300:e.category==='E'?150:70,estimate:false,protected5:false,reason:'파워콘텐츠는 정보 전달형 광고로 70~500원 한도 차등; 파워링크 PC5 관리와 구분'}:policy(k.keyword,e,legacy.has(k.nccKeywordId));rows.push({id:k.nccKeywordId,gid:g.nccAdgroupId,cid:c.nccCampaignId,keyword:k.keyword,groupType:g.adgroupType,category:e.category,priority:e.priority_score,branch:e.branch,geo:e.geo_zone,flags:e.review_flags,...p,oldBid:k.bidAmt,oldGroupBid:k.useGroupBidAmt,oldEffective:Math.round((k.useGroupBidAmt?g.bidAmt:k.bidAmt)*(g.pcNetworkBidWeight??100)/100),weight:g.pcNetworkBidWeight??100,oldLock:k.userLock,groupLock:g.userLock,campaignLock:c.userLock,enabled:!k.userLock&&!g.userLock&&!c.userLock,group:g.name,campaign:c.name,snapshotAt:item.at});}}
 assert(rows.length===meta.keywordInstances+npc.reduce((s,x)=>s+x.keywords.length,0));assert(new Set(rows.map(x=>x.id)).size===rows.length);
 const file=path.join(D,'estimates.jsonl'),est=new Map(fs.existsSync(file)?fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map(l=>{const x=JSON.parse(l);return[x.nccKeywordId,x]}):[]),todo=rows.filter(x=>x.estimate&&!est.has(x.id));const chunks=[];for(let i=0;i<todo.length;i+=100)chunks.push(todo.slice(i,i+100));let done=0;
 const rr=await pool(chunks,4,async chunk=>{const r=await req('POST','/estimate/average-position-bid/id',{device:'PC',items:chunk.map(x=>({key:x.id,position:5}))},441986,5);if(!Array.isArray(r?.estimate))throw Error('Invalid estimate');const rm=new Map(r.estimate.map(x=>[x.nccKeywordId,x]));for(const x of chunk){const e=rm.get(x.id);if(!e||!Number.isFinite(e.bid)||e.bid<=0)throw Error('Missing estimate '+x.id);est.set(x.id,e);fs.appendFileSync(file,JSON.stringify({...e,at:new Date().toISOString()})+'\n');}if(++done%25===0)console.log('estimate batches',done,'/',chunks.length);return true;});if(rr.some(x=>x!==true))throw Error('Estimate errors '+JSON.stringify(rr.filter(x=>x!==true)));
 for(const r of rows){r.pc5=r.estimate?est.get(r.id).bid:null;Object.assign(r,calculate(r,r.pc5,r.weight));if(!r.estimate){const g=gm.get(r.gid),oldBase=r.oldGroupBid?g.bidAmt:r.oldBid;r.bid=Math.max(70,Math.min(oldBase,r.bid));r.effective=Math.round(r.bid*r.weight/100);r.reason+='; 기존보다 낮거나 동일하게만 적용';assert(r.effective<=r.oldEffective);}r.change=r.oldGroupBid||r.oldBid!==r.bid;}
 const summary={at:new Date().toISOString(),all:rows.length,unique:new Set(rows.map(x=>x.keyword)).size,changes:rows.filter(x=>x.change).length,increases:rows.filter(x=>x.change&&x.effective>x.oldEffective).length,decreases:rows.filter(x=>x.change&&x.effective<x.oldEffective).length,enabledChanges:rows.filter(x=>x.change&&x.enabled).length,protected:rows.filter(x=>x.protected5).length,protectedEnabled:rows.filter(x=>x.protected5&&x.enabled).length,capped:rows.filter(x=>x.estimateCapped).length,protectedCapped:rows.filter(x=>x.protected5&&x.estimateCapped).length,tiers:{}};for(const r of rows){const t=summary.tiers[r.tier]||(summary.tiers[r.tier]={all:0,changed:0,enabled:0,minPC:Infinity,maxPC:0});t.all++;t.changed+=+r.change;t.enabled+=+r.enabled;t.minPC=Math.min(t.minPC,r.effective);t.maxPC=Math.max(t.maxPC,r.effective);}
 save('plan',rows);save('plan_summary',summary);console.log(JSON.stringify(summary,null,2));
})().catch(e=>{save('plan_error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
