const fs=require('fs'),path=require('path'),assert=require('assert');const {req}=require('./_sojam_naver');const D=path.join(__dirname,'reports/kiness_budget450_delivery_20260909');const read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
(async()=>{
 const recent=read('blog_recent').find(x=>x.link.includes('224360614586'));assert(recent&&recent.pubDate.includes('28 Jul 2026'));const url='https://blog.naver.com/kikiwar82/224360614586';
 const source=read('ads').flatMap(x=>x.ads).find(a=>a.ad?.contentIssueDate==='2026-01-21');assert(source?.ad?.imagePath);const {contentImages,imageCount,representImage,useContentImage,...base}=source.ad;
 const ad={...base,contentIssueDate:'2026-07-28',headline:'키성장과 소아비만, 예상키 알아보기',description:'어린이키성장, 예상키, 소아비만 때문에 성장클리닉을 찾고 있나요? 키네스 공식 글에서 성장판검사와 성장관리의 차이, 수면과 영양, 운동과 자세 등 키크는방법을 찾기 전 점검할 항목을 확인하세요.',pc:{...base.pc,final:url},mobile:{...base.mobile,final:url}};
 assert(ad.description.length>=80&&ad.description.length<=110);
 const groups=['grp-a001-03-000000027896008','grp-a001-03-000000031320537'];save('content_restore_plan',{at:new Date().toISOString(),sourceArticle:recent,sourceCreativeId:source.nccAdId,groups,ad,existingImageVisuallyReviewed:true});const made=[];
 for(const gid of groups){const current=await req('GET','/ncc/ads?nccAdgroupId='+gid,null,441986);assert(Array.isArray(current));let item=current.find(a=>a.ad?.pc?.final===url&&a.ad?.headline===ad.headline);if(!item){item=await req('POST','/ncc/ads',{nccAdgroupId:gid,type:'CONTENTS_AD_INFORMATION',ad,userLock:false},441986,1);assert(item?.nccAdId);}made.push(item);save('content_restore_created',made);}
 const verified=[];for(const a of made){const current=await req('GET','/ncc/ads?nccAdgroupId='+a.nccAdgroupId,null,441986);const v=current.find(x=>x.nccAdId===a.nccAdId);assert(v&&v.ad.contentIssueDate==='2026-07-28'&&v.ad.pc.final===url&&!v.userLock);verified.push(v);}save('content_restore_verified',verified);console.log(verified.map(a=>({id:a.nccAdId,group:a.nccAdgroupId,status:a.status,reason:a.statusReason,inspect:a.inspectStatus})));
})().catch(e=>{save('content_restore_error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
