const fs=require('fs'),path=require('path');const {geo,mappings}=require('./_kiness_review_rubric');
const D=path.join(__dirname,'reports','kiness_20260914'),read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v,null,1));
const regionDictionary=new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'_haeul_w2_regions.json'),'utf8')));
const getGeo=k=>{const g=geo(k);if(g.token)return g;const m=k.match(/^(.+?)(?:키성장|성장)(?:클리닉|크리닉)/);if(m&&regionDictionary.has(m[1]))return{token:m[1],branch:'',zone:'dictionary_region',confidence:'로컬 행정구역 어휘 완전일치; 지점 배정 미확인'};return g;};
const cm=new Map(read('campaigns').map(x=>[x.nccCampaignId,x])),gm=new Map(read('groups').map(x=>[x.nccAdgroupId,x]));
const master=fs.readFileSync(path.join(D,'Keyword.tsv'),'utf8').split('\n').filter(l=>l.trim()).map(l=>l.replace(/\r$/,'').split('\t'));if(master.some(c=>c.length!==13||c[0]!=='441986'))throw Error('schema');
const stats=new Map();for(const l of fs.readFileSync(path.join(D,'AD.tsv'),'utf8').split('\n').filter(Boolean)){const c=l.replace(/\r$/,'').split('\t');if(c.length!==14)throw Error('AD schema');const a=stats.get(c[4])||{imps:0,clicks:0,cost:0};a.imps+=+c[9];a.clicks+=+c[10];a.cost+=+c[11];stats.set(c[4],a);}
const regional=[];const unknown=[];
for(const c of master){const keyword=c[3];if(!/(?:키성장|성장)(?:클리닉|크리닉)/.test(keyword)||/키네스/.test(keyword))continue;const g=gm.get(c[1]),camp=cm.get(g.nccCampaignId),loc=getGeo(keyword),s=stats.get(c[2])||{};const head=keyword.match(/^(.+?)(?:키성장|성장)(?:클리닉|크리닉)$/)?.[1];const exact=!!head&&(regionDictionary.has(head)||head===loc.token||/^(?:동|구|시|군|읍|면|역)$/.test(head.slice(loc.token.length)));const x={id:c[2],keyword,gid:c[1],cid:g.nccCampaignId,group:g.name,campaign:camp.name,geo:loc,exact,bid:c[9]==='1'?g.bidAmt:+c[4],useGroupBid:c[9]==='1',keywordLock:c[7]==='1',masterCode:c[8],enabled:c[7]!=='1'&&!g.userLock&&!camp.userLock,pcWeight:g.pcNetworkBidWeight,moWeight:g.mobileNetworkBidWeight,groupStatus:g.status,campaignStatus:camp.status,yImps:s.imps||0,yClicks:s.clicks||0};
if(loc.token)regional.push(x);else unknown.push(x);}
const byKey=new Map();for(const r of regional){let x=byKey.get(r.keyword);if(!x){x={keyword:r.keyword,geo:r.geo,yImps:0,yClicks:0,registrations:[],enabled:0};byKey.set(r.keyword,x);}x.yImps+=r.yImps;x.yClicks+=r.yClicks;x.enabled+=+r.enabled;x.registrations.push(r);}
save('regional_instances',regional);save('regional_unique',[...byKey.values()]);save('clinic_nonregional_or_unmapped',unknown);
const regions=new Set(regional.filter(r=>r.exact).map(r=>{const m=r.keyword.match(/^(.+?)(?:키성장|성장)클리닉$/);return m?.[1]}).filter(Boolean));
const existing=new Set(master.map(c=>c[3]));const gaps=[];for(const region of regions)for(const tail of ['성장클리닉','키성장클리닉']){const kw=region+tail;if(!existing.has(kw))gaps.push({keyword:kw,region,geo:geo(kw)});}save('missing_pairs',gaps);
console.log(JSON.stringify({regionalInstances:regional.length,unique:byKey.size,enabledUnique:[...byKey.values()].filter(x=>x.enabled).length,yesterdayImpressed:[...byKey.values()].filter(x=>x.yImps).length,exactUnique:[...byKey.values()].filter(x=>x.registrations.some(r=>r.exact)).length,missingPairs:gaps.length,unknownUnique:new Set(unknown.map(r=>r.keyword)).size}));
console.log('TOP',JSON.stringify([...byKey.values()].filter(x=>x.yImps).sort((a,b)=>b.yImps-a.yImps).slice(0,20).map(x=>({keyword:x.keyword,imp:x.yImps,clicks:x.yClicks,enabled:x.enabled}))));
