const fs=require('fs'),path=require('path');
const {req,pool,sleep}=require('./_sojam_naver');
const D=path.join(__dirname,'reports','kiness_20260914');fs.mkdirSync(D,{recursive:true});
const save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
const call=async(m,p,b)=>{const r=await req(m,p,b,441986,3);if(r===undefined)throw Error('No response '+p);return r;};
const chunks=(a,n)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
async function stats(ids,day){const res=await pool(chunks(ids,50),4,b=>call('GET','/stats?ids='+encodeURIComponent(b.join(','))+'&fields='+encodeURIComponent(JSON.stringify(['impCnt','clkCnt','salesAmt','avgRnk','pcNxAvgRnk','mblNxAvgRnk']))+'&timeRange='+encodeURIComponent(JSON.stringify({since:day,until:day}))+'&breakdown=pcMblTp'));if(res.some(x=>!Array.isArray(x.data)))throw Error('Incomplete stats');return res.flatMap(x=>x.data);}
async function report(type){let job=await call('POST','/stat-reports',{reportTp:type,statDt:'20260913'});if(!job.reportJobId)throw Error('No job');for(let i=0;i<90;i++){job=await call('GET','/stat-reports/'+job.reportJobId);if(['BUILT','NONE','ERROR'].includes(job.status))break;await sleep(2000);}save('job_'+type,job);if(job.status==='NONE'){fs.writeFileSync(path.join(D,type+'.tsv'),'');return;}if(job.status!=='BUILT')throw Error('report '+type+' '+job.status);const u=new URL(job.downloadUrl);if(u.hostname!=='api.searchad.naver.com')throw Error('host');const t=await call('GET',u.pathname+u.search);if(typeof t!=='string')throw Error('report format');fs.writeFileSync(path.join(D,type+'.tsv'),t);console.log('REPORT',type,t.length);}
async function inventory(){const campaigns=await call('GET','/ncc/campaigns');save('campaigns',campaigns);save('shared_budgets',await call('GET','/ncc/shared-budgets'));const cs=await stats(campaigns.map(c=>c.nccCampaignId),'2026-09-13');save('campaign_yesterday',cs);console.log('YESTERDAY',JSON.stringify(cs.reduce((a,x)=>({cost:a.cost+x.salesAmt,clicks:a.clicks+x.clkCnt,imps:a.imps+x.impCnt}),{cost:0,clicks:0,imps:0})));
const gb=await pool(campaigns,5,c=>call('GET','/ncc/adgroups?nccCampaignId='+c.nccCampaignId));if(!gb.every(Array.isArray))throw Error('groups');const groups=gb.flat();save('groups',groups);
const file=path.join(D,'inventory.jsonl'),cache=new Map(fs.existsSync(file)?fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map(l=>{const x=JSON.parse(l);return[x.gid,x]}):[]);let count=0;
let job=await call('POST','/master-reports',{item:'Keyword'});for(let i=0;i<90;i++){job=await call('GET','/master-reports/'+job.id);if(['BUILT','NONE','ERROR'].includes(job.status))break;await sleep(2000);}save('master_job',job);if(job.status!=='BUILT')throw Error('Master report '+job.status);const u=new URL(job.downloadUrl);if(u.hostname!=='api.searchad.naver.com')throw Error('host');const master=await call('GET',u.pathname+u.search);if(typeof master!=='string')throw Error('Master format');fs.writeFileSync(path.join(D,'Keyword.tsv'),master);
const byGroup=new Map(groups.map(g=>[g.nccAdgroupId,[]]));for(const line of master.split('\n').filter(l=>l.trim())){const c=line.replace(/\r$/,'').split('\t');if(c.length!==13||c[0]!=='441986')throw Error('Master schema '+c.length);if(!byGroup.has(c[1]))throw Error('Unknown group');byGroup.get(c[1]).push({nccKeywordId:c[2],nccAdgroupId:c[1],keyword:c[3],bidAmt:+c[4],userLock:c[7]==='1',masterStatusCode:c[8],useGroupBidAmt:c[9]==='1'});}
const inv=groups.map(g=>({gid:g.nccAdgroupId,keywords:byGroup.get(g.nccAdgroupId)}));save('inventory',inv);console.log('MASTER_KEYWORDS',inv.reduce((s,x)=>s+x.keywords.length,0));
const gm=new Map(groups.map(g=>[g.nccAdgroupId,g])),cm=new Map(campaigns.map(c=>[c.nccCampaignId,c]));const targets=[];for(const x of inv)for(const k of x.keywords){if(!/(?:키성장|성장)(?:클리닉|크리닉)/.test(k.keyword))continue;const g=gm.get(x.gid),c=cm.get(g.nccCampaignId);targets.push({id:k.nccKeywordId,keyword:k.keyword,gid:x.gid,cid:c.nccCampaignId,group:g.name,campaign:c.name,bid:k.useGroupBidAmt?g.bidAmt:k.bidAmt,pcWeight:g.pcNetworkBidWeight,moWeight:g.mobileNetworkBidWeight,enabled:!k.userLock&&!g.userLock&&!c.userLock,keywordStatus:k.status,groupStatus:g.status,campaignStatus:c.status,keywordLock:k.userLock});}save('targets',targets);for(const [name,day] of [['yesterday','2026-09-13'],['today','2026-09-14']])save('rank_'+name,await stats(targets.map(t=>t.id),day));save('meta',{completedAt:new Date().toISOString(),customerId:441986,day:'2026-09-13',groups:groups.length,keywords:inv.reduce((s,x)=>s+x.keywords.length,0),targetInstances:targets.length,uniqueTargets:new Set(targets.map(t=>t.keyword)).size});console.log('AUDIT_DONE',targets.length);}
(async()=>{const r=await Promise.allSettled([inventory(),report('AD'),report('EXPKEYWORD')]);for(const x of r)if(x.status==='rejected')throw x.reason;})().catch(e=>{save('error',{error:String(e)});console.error(e);process.exitCode=1;});
