const fs=require('fs'),path=require('path');const {req,pool}=require('./_sojam_naver');
const D=path.join(__dirname,'reports/kiness_mobile_budget_20260909');fs.mkdirSync(D,{recursive:true});const save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
const call=async(m,p,b)=>{const r=await req(m,p,b,441986,4);if(r===undefined)throw Error('Missing response '+p);return r;};
(async()=>{
 const camps=await call('GET','/ncc/campaigns');save('campaigns_live',camps);
 let groups;if(fs.existsSync(path.join(D,'groups_before.json')))groups=JSON.parse(fs.readFileSync(path.join(D,'groups_before.json'),'utf8'));else {const batches=await pool(camps,6,c=>call('GET','/ncc/adgroups?nccCampaignId='+c.nccCampaignId));if(batches.some(x=>!Array.isArray(x)))throw Error('Incomplete groups');groups=batches.flat();save('groups_before',groups);}console.log('groups',groups.length);
 const targets=JSON.parse(fs.readFileSync(path.join(__dirname,'reports/kiness_click_rank_20260909/rank_targets.json'),'utf8')),gids=[...new Set(targets.map(x=>x.gid))];
 const inv=await pool(gids,6,async gid=>({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)}));if(inv.some(x=>!Array.isArray(x.keywords)))throw Error('Incomplete inventory');save('inventory_before',inv);console.log('target groups',gids.length);
 const jobs=[];for(const device of ['PC','MOBILE'])for(let i=0;i<targets.length;i+=100)jobs.push({device,rows:targets.slice(i,i+100)});
 const estimates=await pool(jobs,4,async j=>{const r=await call('POST','/estimate/average-position-bid/id',{device:j.device,items:j.rows.map(x=>({key:x.id,position:5}))});if(!Array.isArray(r.estimate)||r.estimate.length!==j.rows.length)throw Error('Incomplete '+j.device);return {device:j.device,at:new Date().toISOString(),data:r.estimate};});if(estimates.some(x=>!x.data))throw Error(JSON.stringify(estimates.filter(x=>!x.data)));save('estimates',estimates);console.log('estimates complete',targets.length);
 for(const [name,since,until]of [['yesterday','2026-09-08','2026-09-08'],['today','2026-09-09','2026-09-09'],['week','2026-09-02','2026-09-08']]){const data=[];for(let i=0;i<camps.length;i+=50){const r=await call('GET','/stats?ids='+encodeURIComponent(camps.slice(i,i+50).map(c=>c.nccCampaignId).join(','))+'&fields='+encodeURIComponent(JSON.stringify(['salesAmt','clkCnt','impCnt']))+'&timeRange='+encodeURIComponent(JSON.stringify({since,until})));if(!Array.isArray(r.data))throw Error('Stats missing');data.push(r);}save('stats_'+name,data);console.log(name,data.flatMap(x=>x.data).reduce((a,x)=>({cost:a.cost+(x.salesAmt||0),clicks:a.clicks+(x.clkCnt||0),imps:a.imps+(x.impCnt||0)}),{cost:0,clicks:0,imps:0}));}
 save('collect_done',{at:new Date().toISOString(),groups:groups.length,targets:targets.length});
})().catch(e=>{save('collect_error',{error:String(e)});console.error(e);process.exitCode=1;});
