const fs=require('fs'),path=require('path');const {req,pool}=require('./_sojam_naver');const D=path.join(__dirname,'reports/kiness_budget450_delivery_20260909'),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));const call=async p=>{const r=await req('GET',p,null,441986,4);if(r===undefined)throw Error('Missing '+p);return r;};
(async()=>{
 const camps=await call('/ncc/campaigns');save('campaigns',camps);const cm=new Map(camps.map(c=>[c.nccCampaignId,c]));const gb=await pool(camps,6,c=>call('/ncc/adgroups?nccCampaignId='+c.nccCampaignId));if(gb.some(x=>!Array.isArray(x)))throw Error('Groups incomplete');const groups=gb.flat();save('groups',groups);const active=groups.filter(g=>!g.userLock&&!cm.get(g.nccCampaignId).userLock);console.log('groups',groups.length,'active',active.length);
 save('channels',await call('/ncc/channels'));
 const ads=await pool(active,6,async g=>({gid:g.nccAdgroupId,ads:await call('/ncc/ads?nccAdgroupId='+g.nccAdgroupId)}));if(ads.some(x=>!Array.isArray(x.ads)))throw Error('Ads incomplete');save('ads',ads);
 const web=active.filter(g=>g.adgroupType==='WEB_SITE');const inv=await pool(web,6,async g=>({gid:g.nccAdgroupId,keywords:await call('/ncc/keywords?nccAdgroupId='+g.nccAdgroupId)}));if(inv.some(x=>!Array.isArray(x.keywords)))throw Error('Keywords incomplete');save('inventory',inv);
 const tb=[];for(let i=0;i<active.length;i+=20)tb.push(active.slice(i,i+20));const targets=await pool(tb,4,x=>call('/ncc/targets?ownerIds='+encodeURIComponent(x.map(g=>g.nccAdgroupId).join(','))));if(targets.some(x=>!Array.isArray(x)))throw Error('Targeting incomplete');save('targeting',targets.flat());
 const high=JSON.parse(fs.readFileSync(path.join(__dirname,'reports/kiness_delivery_boost_20260909/plan.json'),'utf8')),sets=[['campaigns',camps.map(c=>c.nccCampaignId)],['groups',active.map(g=>g.nccAdgroupId)],['keywords',high.map(x=>x.id)]];
 for(const [name,ids]of sets){const chunks=[];for(let i=0;i<ids.length;i+=50)chunks.push(ids.slice(i,i+50));const data=await pool(chunks,5,async x=>{const r=await call('/stats?ids='+encodeURIComponent(x.join(','))+'&fields='+encodeURIComponent(JSON.stringify(['impCnt','clkCnt','salesAmt','pcNxAvgRnk','mblNxAvgRnk','recentAvgRnk']))+'&timeRange='+encodeURIComponent(JSON.stringify({since:'2026-09-09',until:'2026-09-09'})));if(!Array.isArray(r.data))throw Error('Incomplete stats');return r;});if(data.some(x=>!x.data))throw Error('Stats failed '+name);save('stats_'+name,data);console.log(name,'records',data.reduce((s,x)=>s+x.data.length,0));}
 save('audit_done',{at:new Date().toISOString(),campaigns:camps.length,groups:groups.length,active:active.length,keywordInventory:inv.reduce((s,x)=>s+x.keywords.length,0),highIntentStats:high.length});
})().catch(e=>{save('audit_error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
