const fs=require('fs'),path=require('path'),assert=require('assert');const {req,pool}=require('./_sojam_naver');
const D=path.join(__dirname,'reports','kiness_bids_20260909'),read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
const get=async p=>{const r=await req('GET',p,null,441986,5);if(r===undefined)throw Error('Missing response');return r;};
const state=fs.existsSync(path.join(D,'apply_state.json'))?read('apply_state'):{startedAt:new Date().toISOString(),applied:0,batches:[],errors:[]};
(async()=>{
 const rows=read('plan'),changes=rows.filter(x=>x.change).sort((a,b)=>(a.effective-a.oldEffective)-(b.effective-b.oldEffective));const gids=[...new Set(changes.map(x=>x.gid))];
 const bs=await get('/ncc/shared-budgets');assert(bs.some(x=>x.name==='키네스_문의확대_총검색예산_0908'&&x.dailyBudget===198000),'Search budget guard');save('budgets_before_apply',bs);
 const liveGr=await pool(gids,6,gid=>get('/ncc/adgroups/'+gid));if(liveGr.some(g=>!g?.nccAdgroupId))throw Error('Live groups incomplete');const gm=new Map(liveGr.map(g=>[g.nccAdgroupId,g]));
 for(const r of changes)assert.equal(gm.get(r.gid).pcNetworkBidWeight??100,r.weight,'PC weight changed '+r.gid);
 if(!state.batches.length){const pre=await pool(gids,6,async gid=>({gid,keywords:await get('/ncc/keywords?nccAdgroupId='+gid)}));if(pre.some(x=>!Array.isArray(x.keywords)))throw Error('Preflight incomplete');save('preflight_inventory',pre);const km=new Map(pre.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));const drift=[];for(const r of changes){const k=km.get(r.id);if(!k||k.bidAmt!==r.oldBid||k.useGroupBidAmt!==r.oldGroupBid)drift.push({id:r.id,keyword:r.keyword,before:r.oldBid,live:k?.bidAmt});}save('preflight_drift',drift);assert.equal(drift.length,0,'Concurrent edits detected');}
 for(let i=0;i<changes.length;i+=100){if(state.batches.includes(i))continue;const chunk=changes.slice(i,i+100);const response=await req('PUT','/ncc/keywords?fields=bidAmt',chunk.map(r=>({nccKeywordId:r.id,nccAdgroupId:r.gid,bidAmt:r.bid,useGroupBidAmt:false})),441986,1);if(!Array.isArray(response)||response.length!==chunk.length)throw Error('Incomplete mutation response at '+i);const rm=new Map(response.map(k=>[k.nccKeywordId,k]));for(const r of chunk){const k=rm.get(r.id);assert(k&&!k.code&&!k.error&&k.bidAmt===r.bid&&k.useGroupBidAmt===false,'Mutation verification '+r.id);}state.applied+=chunk.length;state.batches.push(i);save('apply_state',state);if(i%5000===0)console.log('applied',state.applied,'/',changes.length);}
 const check=await pool(gids,6,async gid=>({gid,keywords:await get('/ncc/keywords?nccAdgroupId='+gid)}));if(check.some(x=>!Array.isArray(x.keywords)))throw Error('Final verification incomplete');save('after_inventory',check);const km=new Map(check.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));const errors=[];for(const r of changes){const k=km.get(r.id);if(!k||k.bidAmt!==r.bid||k.useGroupBidAmt!==false)errors.push({id:r.id,keyword:r.keyword,wanted:r.bid,actual:k?.bidAmt});}save('verification_errors',errors);assert.equal(errors.length,0,'Final mismatch');
 const afterBudgets=await get('/ncc/shared-budgets');save('budgets_after',afterBudgets);for(const b of bs)assert.equal(afterBudgets.find(x=>x.sharedBudgetId===b.sharedBudgetId)?.dailyBudget,b.dailyBudget,'Budget changed during run');
 const pre=read('preflight_inventory'),beforeMap=new Map(pre.flatMap(x=>x.keywords).map(k=>[k.nccKeywordId,k]));const lockDrift=check.flatMap(x=>x.keywords).filter(k=>beforeMap.has(k.nccKeywordId)&&beforeMap.get(k.nccKeywordId).userLock!==k.userLock).map(k=>k.nccKeywordId);save('lock_drift',lockDrift);
 const monitor=rows.filter(r=>r.protected5&&r.enabled).map(r=>({kw:r.keyword,id:r.id,gid:r.gid}));save('monitor_targets',monitor);
 state.completedAt=new Date().toISOString();state.verified=changes.length;state.errors=[];state.userLockDrift=lockDrift.length;state.budgetUnchanged=true;save('apply_state',state);console.log('APPLY VERIFIED',JSON.stringify({applied:state.applied,verified:state.verified,lockDrift:lockDrift.length,budgetUnchanged:true}));
})().catch(e=>{state.errors.push({at:new Date().toISOString(),error:String(e)});save('apply_state',state);console.error(e);process.exitCode=1;});
