const fs=require('fs'),path=require('path');const {req,pool}=require('./_sojam_naver');
const BASE=path.join(__dirname,'reports','kiness_20260914'),D=path.join(BASE,'all_regions');fs.mkdirSync(D,{recursive:true});
const read=(n,d=D)=>JSON.parse(fs.readFileSync(path.join(d,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v,null,1));
const call=async(m,p,b)=>{const r=await req(m,p,b,441986,m==='GET'||p.startsWith('/estimate')?4:1);if(r===undefined)throw Error('No response '+p);return r;};
const chunks=(a,n)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
async function collect(){
 const scope=read('regional_unique',BASE),prior=read('applied',BASE),gids=[...new Set(scope.flatMap(r=>r.registrations.map(x=>x.gid)).concat(prior.created.map(x=>x.gid)))];
 save('scope',{at:new Date().toISOString(),sourceSheet:'지역키워드순위요약',keywords:scope.map(r=>r.keyword),additionalCreated:prior.created.map(x=>x.keyword)});
 const campaigns=await call('GET','/ncc/campaigns');save('campaigns',campaigns);const cm=new Map(campaigns.map(c=>[c.nccCampaignId,c]));save('budgets',await call('GET','/ncc/shared-budgets'));
 const live=await pool(gids,5,async gid=>({gid,group:await call('GET','/ncc/adgroups/'+gid),keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid),ads:await call('GET','/ncc/ads?nccAdgroupId='+gid)}));save('snapshot',live);if(live.some(x=>!Array.isArray(x.keywords)||!Array.isArray(x.ads)))throw Error('Incomplete snapshot '+JSON.stringify(live.filter(x=>x.__err)));const gm=new Map(live.map(x=>[x.gid,x]));
 const scoped=scope.concat(prior.created.filter(x=>!scope.some(r=>r.keyword===x.keyword)).map(x=>({keyword:x.keyword,registrations:[x]})));
 const choices=scoped.map(r=>{const candidates=r.registrations.map(x=>{const s=gm.get(x.gid),k=s.keywords.find(k=>k.nccKeywordId===x.id);if(!k)throw Error('Deleted target '+r.keyword);const g=s.group,c=cm.get(g.nccCampaignId),t=g.targets?.find(x=>x.targetTp==='PC_MOBILE_TARGET')?.target;const adCount=s.ads.filter(a=>!a.userLock&&a.status==='ELIGIBLE').length;return {keyword:r.keyword,id:k.nccKeywordId,gid:x.gid,cid:g.nccCampaignId,group:g.name,bid:k.useGroupBidAmt?g.bidAmt:k.bidAmt,useGroupBidAmt:k.useGroupBidAmt,keywordLock:k.userLock,keywordStatus:k.status,inspectStatus:k.inspectStatus,keywordReason:k.statusReason,groupStatus:g.status,campaignStatus:c.status,servingAds:adCount,pcWeight:g.pcNetworkBidWeight,moWeight:g.mobileNetworkBidWeight,pcTarget:t?.pc??true,moTarget:t?.mobile??true,otherwiseUsable:!g.userLock&&g.status==='ELIGIBLE'&&!c.userLock&&c.status==='ELIGIBLE'&&adCount>0&&k.inspectStatus==='APPROVED',usable:!k.userLock&&k.status==='ELIGIBLE'&&!g.userLock&&g.status==='ELIGIBLE'&&!c.userLock&&c.status==='ELIGIBLE'&&adCount>0,quality:k.nccQi?.qiGrade,adRelevance:k.adRelevanceScore,expectedClick:k.expectedClickScore};});candidates.sort((a,b)=>+b.usable-+a.usable||+b.otherwiseUsable-+a.otherwiseUsable||b.bid-a.bid);return candidates[0];});save('choices',choices);console.log('LIVE',choices.length,'usable',choices.filter(x=>x.usable).length);
 const jobs=[];for(const device of ['PC','MOBILE'])for(const b of chunks(choices,200))jobs.push({device,rows:b});
 const estimates=await pool(jobs,4,async j=>({device:j.device,requestedIds:j.rows.map(x=>x.id),response:await call('POST','/estimate/exposure-minimum-bid/id',{device:j.device,period:'MONTH',items:j.rows.map(x=>x.id)})}));save('minimum_estimates',estimates);if(estimates.some(x=>!Array.isArray(x.response?.estimate)))throw Error('Incomplete minimum estimates '+JSON.stringify(estimates.filter(x=>!x.response?.estimate)));
 const em=new Map();for(const b of estimates)for(const e of b.response.estimate){const x=em.get(e.nccKeywordId)||{};x[b.device]=e.bid;em.set(e.nccKeywordId,x);}
 const proposed=choices.map(x=>{const e=em.get(x.id);if(!e||!Number.isFinite(e.PC)||!Number.isFinite(e.MOBILE))throw Error('Missing per-device estimate '+x.keyword);const need=x.pcWeight>0&&x.moWeight>0?Math.ceil(Math.max(e.PC*100/x.pcWeight,e.MOBILE*100/x.moWeight)*1.15/10)*10:null;return {...x,pcMinimum:e.PC,moMinimum:e.MOBILE,requiredBid:need,proposedBid:Math.max(x.bid,Math.min(100000,Math.max(700,need||0))),enableKeyword:x.keywordLock&&x.otherwiseUsable,abovePlatformCap:need>100000,estimateIsActualRank:false};});save('plan',proposed);console.log('SUMMARY',JSON.stringify({scope:scope.length,total:choices.length,raises:proposed.filter(x=>x.proposedBid>x.bid).length,enables:proposed.filter(x=>x.enableKeyword).map(x=>x.keyword),otherBlocks:proposed.filter(x=>!x.usable&&!x.enableKeyword).map(x=>({keyword:x.keyword,status:x.keywordStatus,group:x.groupStatus})),deviceBlocked:proposed.filter(x=>!x.pcTarget||!x.moTarget||!x.pcWeight||!x.moWeight).length,overCap:proposed.filter(x=>x.abovePlatformCap).length,top:proposed.filter(x=>x.proposedBid>x.bid).sort((a,b)=>b.proposedBid-a.proposedBid).slice(0,25).map(x=>({keyword:x.keyword,from:x.bid,to:x.proposedBid,pcMin:x.pcMinimum,moMin:x.moMinimum}))}));
}
async function verify(){
 const plan=read('plan'),state=read('applied'),gids=[...new Set(plan.map(x=>x.gid))];
 const campaigns=await call('GET','/ncc/campaigns'),cm=new Map(campaigns.map(x=>[x.nccCampaignId,x]));
 const after=await pool(gids,4,async gid=>({gid,group:await call('GET','/ncc/adgroups/'+gid),keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid),ads:await call('GET','/ncc/ads?nccAdgroupId='+gid)}));save('verified_snapshot',after);if(after.some(x=>!Array.isArray(x.keywords)||!Array.isArray(x.ads)))throw Error('Incomplete live verification');const gm=new Map(after.map(x=>[x.gid,x]));
 const rows=plan.map(p=>{const s=gm.get(p.gid),g=s.group,c=cm.get(g.nccCampaignId),k=s.keywords.find(k=>k.nccKeywordId===p.id),t=g.targets?.find(x=>x.targetTp==='PC_MOBILE_TARGET')?.target,bid=k?(k.useGroupBidAmt?g.bidAmt:k.bidAmt):null,servingAds=s.ads.filter(a=>!a.userLock&&a.status==='ELIGIBLE').length;const issues=[];if(!k||k.userLock||k.status!=='ELIGIBLE')issues.push('키워드 송출불가');if(g.userLock||g.status!=='ELIGIBLE'||c.userLock||c.status!=='ELIGIBLE')issues.push('상위 송출불가');if(!servingAds)issues.push('소재 송출불가');if(t?.pc===false||t?.mobile===false||g.pcNetworkBidWeight<=0||g.mobileNetworkBidWeight<=0)issues.push('기기 제한');if(bid<p.proposedBid)issues.push('입찰 하한 미달');return {...p,bid,keywordStatus:k?.status,inspectStatus:k?.inspectStatus,keywordLock:k?.userLock,servingAds,usable:issues.length===0,issues,verifiedAt:new Date().toISOString()};});save('verified_rows',rows);
 const budgets=await call('GET','/ncc/shared-budgets');save('verified_budgets',budgets);const daily=budgets.find(x=>x.sharedBudgetId==='nsb-a001-01-000000000073065')?.dailyBudget;
 const summary={at:new Date().toISOString(),total:rows.length,sourceSheetKeywords:read('scope').keywords.length,eligible:rows.filter(x=>x.usable).length,failures:rows.filter(x=>!x.usable).map(x=>({keyword:x.keyword,issues:x.issues})),dailyBudget:daily,budgetMatches:daily===200000,bidChanges:state.bids.length,enabled:state.enabled.length,actualExposureGuaranteed:false};save('verification',summary);console.log('VERIFIED',JSON.stringify(summary));if(summary.failures.length||!summary.budgetMatches)throw Error('Verification failed');return summary;
}
async function apply(){
 const plan=read('plan'),budgets=await call('GET','/ncc/shared-budgets');if(budgets.find(x=>x.sharedBudgetId==='nsb-a001-01-000000000073065')?.dailyBudget!==200000)throw Error('Budget changed; review needed');
 const state=fs.existsSync(path.join(D,'applied.json'))?read('applied'):{startedAt:new Date().toISOString(),bids:[],enabled:[],protectedKeywordIds:plan.map(x=>x.id),errors:[]};save('applied',state);
 try{
  const moves=plan.filter(x=>x.proposedBid>x.bid&&!state.bids.some(y=>y.id===x.id)),unlocks=plan.filter(x=>x.enableKeyword&&!state.enabled.some(y=>y.id===x.id));
  const gids=[...new Set([...moves,...unlocks].map(x=>x.gid))];const pre=await pool(gids,4,async gid=>({gid,keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid)}));if(pre.some(x=>!Array.isArray(x.keywords)))throw Error('Preflight incomplete');if(!fs.existsSync(path.join(D,'apply_backup.json')))save('apply_backup',pre);const km=new Map(pre.flatMap(x=>x.keywords).map(x=>[x.nccKeywordId,x]));
  for(const p of [...moves,...unlocks]){const k=km.get(p.id);if(!k||k.bidAmt!==p.bid&&!(p.useGroupBidAmt&&k.useGroupBidAmt)||k.userLock!==p.keywordLock)throw Error('Concurrent change '+p.keyword);if(p.proposedBid>100000||p.proposedBid<700||p.proposedBid%10)throw Error('Invalid bid');}
  for(const batch of chunks(moves,100)){const r=await call('PUT','/ncc/keywords?fields=bidAmt',batch.map(x=>({nccKeywordId:x.id,nccAdgroupId:x.gid,bidAmt:x.proposedBid,useGroupBidAmt:false})));if(!Array.isArray(r)||r.length!==batch.length)throw Error('Bid response incomplete');for(const p of batch){const k=r.find(x=>x.nccKeywordId===p.id);if(!k||k.bidAmt!==p.proposedBid||k.useGroupBidAmt)throw Error('Bid failed '+p.keyword);state.bids.push({id:p.id,gid:p.gid,keyword:p.keyword,from:p.bid,to:p.proposedBid,pcMinimum:p.pcMinimum,moMinimum:p.moMinimum,at:new Date().toISOString()});}save('applied',state);console.log('BIDS_APPLIED',state.bids.length);}
  for(const batch of chunks(unlocks,100)){const r=await call('PUT','/ncc/keywords?fields=userLock',batch.map(x=>({nccKeywordId:x.id,nccAdgroupId:x.gid,userLock:false})));if(!Array.isArray(r)||r.length!==batch.length||r.some(x=>x.userLock))throw Error('Enable failed');for(const p of batch)state.enabled.push({id:p.id,gid:p.gid,keyword:p.keyword,from:true,to:false,at:new Date().toISOString()});save('applied',state);}
  state.completedAt=new Date().toISOString();save('applied',state);await verify();
 }catch(e){state.errors.push({at:new Date().toISOString(),error:String(e)});save('applied',state);throw e;}
}
(async()=>{const mode=process.argv[2];if(mode==='collect')await collect();else if(mode==='apply')await apply();else if(mode==='verify')await verify();else throw Error('Use collect/apply/verify');})().catch(e=>{save('error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
