const fs=require('fs'),path=require('path');const {req,pool}=require('./_sojam_naver');const D=path.join(__dirname,'reports/kiness_delivery_boost_20260909');const read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
(async()=>{
 const ready=new Set(read('ads').filter(x=>x.ads.some(a=>!a.userLock&&a.status==='ELIGIBLE')).map(x=>x.gid));
 const excluded=read('targets').filter(x=>!ready.has(x.gid));save('excluded_no_creative',excluded);const targets=read('targets').filter(x=>ready.has(x.gid));
 const jobs=[];for(const device of ['PC','MOBILE'])for(let i=0;i<targets.length;i+=100)jobs.push({device,rows:targets.slice(i,i+100)});let done=0;
 const est=await pool(jobs,5,async j=>{const r=await req('POST','/estimate/average-position-bid/id',{device:j.device,items:j.rows.map(x=>({key:x.id,position:j.device==='PC'&&x.protected5?5:3}))},441986,4);if(!Array.isArray(r?.estimate)||r.estimate.length!==j.rows.length)throw Error('Missing estimate');if(++done%50===0)console.log('estimate batches',done,'/',jobs.length);return {device:j.device,at:new Date().toISOString(),data:r.estimate};});if(est.some(x=>!x.data))throw Error('Estimates incomplete');save('estimates',est);
 const pc=new Map(est.filter(x=>x.device==='PC').flatMap(x=>x.data).map(x=>[x.nccKeywordId,x.bid])),mo=new Map(est.filter(x=>x.device==='MOBILE').flatMap(x=>x.data).map(x=>[x.nccKeywordId,x.bid]));
 for(const r of targets){r.pcEstimate=pc.get(r.id);r.mobileEstimate=mo.get(r.id);if(!r.pcEstimate||!r.mobileEstimate)throw Error('Missing positive estimate '+r.id);const direct=/예약|문의|상담|검사비용|검사가격|클리닉비용|클리닉가격/.test(r.keyword);
  r.floor=r.protected5?700:r.category==='A'?500:r.category==='B'?1200:1000;r.cap=r.protected5?100000:r.category==='A'?5000:['B','C'].includes(r.category)?direct?25000:20000:6000;
  r.pcTarget=Math.min(r.cap,Math.max(r.floor,r.pcEstimate*(r.protected5?1.05:1.10)));r.mobileTarget=Math.min(r.cap,Math.max(r.floor,r.mobileEstimate*1.10));
  const wanted=Math.ceil(Math.max(r.pcTarget*100/r.pcWeight,r.mobileTarget*100/r.mobileWeight)/10)*10;r.bid=Math.max(r.oldBase,Math.min(100000,wanted));r.pcEffective=Math.round(r.bid*r.pcWeight/100);r.mobileEffective=Math.round(r.bid*r.mobileWeight/100);r.change=r.bid!==r.oldBase||r.oldGroupBid;r.estimateCapped=r.pcEffective<r.pcEstimate*(r.protected5?1.05:1.1)||r.mobileEffective<r.mobileEstimate*1.1;
 }
 save('plan',targets);const summary={at:new Date().toISOString(),targets:targets.length,changes:targets.filter(r=>r.change).length,excluded:excluded.length,capped:targets.filter(r=>r.estimateCapped).length,tiers:{}};for(const r of targets){const x=summary.tiers[r.tier]||(summary.tiers[r.tier]={all:0,changes:0,min:Infinity,max:0});x.all++;x.changes+=+r.change;x.min=Math.min(x.min,r.bid);x.max=Math.max(x.max,r.bid);}save('plan_summary',summary);console.log(JSON.stringify(summary));
})().catch(e=>{save('plan_error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
