const fs=require('fs'),path=require('path');const {req,pool}=require('./_sojam_naver');
const D=path.join(__dirname,'reports','kiness_20260914'),read=n=>JSON.parse(fs.readFileSync(path.join(D,n+'.json'),'utf8')),save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));
const call=async(m,p,b)=>{const r=await req(m,p,b,441986,3);if(r===undefined)throw Error('No response');return r;};const chunks=(a,n)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
(async()=>{
const rows=read('regional_unique'),gids=[...new Set(rows.flatMap(r=>r.registrations.map(x=>x.gid)))];
const snapshot=await pool(gids,5,async gid=>({gid,group:await call('GET','/ncc/adgroups/'+gid),keywords:await call('GET','/ncc/keywords?nccAdgroupId='+gid),ads:await call('GET','/ncc/ads?nccAdgroupId='+gid)}));if(snapshot.some(x=>!Array.isArray(x.keywords)||!Array.isArray(x.ads)))throw Error('Incomplete diagnostic');save('delivery_snapshot',snapshot);console.log('LIVE_GROUPS',snapshot.length);
const gm=new Map(snapshot.map(x=>[x.gid,x])),cm=new Map((await call('GET','/ncc/campaigns')).map(c=>[c.nccCampaignId,c]));save('delivery_campaigns',[...cm.values()]);save('delivery_budgets',await call('GET','/ncc/shared-budgets'));
const choices=[];for(const r of rows){const candidates=r.registrations.map(x=>{const s=gm.get(x.gid),k=s.keywords.find(k=>k.nccKeywordId===x.id),g=s.group,c=cm.get(g.nccCampaignId);if(!k)throw Error('Missing keyword');return{...x,bid:k.useGroupBidAmt?g.bidAmt:k.bidAmt,keywordStatus:k.status,keywordReason:k.statusReason,keywordLock:k.userLock,groupStatus:g.status,groupLock:g.userLock,campaignStatus:c.status,campaignLock:c.userLock,servingAds:s.ads.filter(a=>a.status==='ELIGIBLE'&&!a.userLock).length,pcWeight:g.pcNetworkBidWeight,moWeight:g.mobileNetworkBidWeight,sharedBudgetId:g.sharedBudgetId,usable:!k.userLock&&!g.userLock&&!c.userLock&&k.status==='ELIGIBLE'&&g.status==='ELIGIBLE'&&c.status==='ELIGIBLE'&&s.ads.some(a=>a.status==='ELIGIBLE'&&!a.userLock)};});candidates.sort((a,b)=>(+b.usable-+a.usable)||b.bid-a.bid);choices.push({...candidates[0],registrations:candidates.length});}save('delivery_choices',choices);
const targets=await pool(chunks(gids,20),4,b=>call('GET','/ncc/targets?ownerIds='+encodeURIComponent(b.join(','))));if(targets.some(x=>!Array.isArray(x)))throw Error('targets');save('delivery_targets',targets.flat());
const jobs=[];for(const device of ['PC','MOBILE'])for(const b of chunks(choices.filter(x=>x.usable),100))jobs.push({device,rows:b});
const est=await pool(jobs,4,async j=>({device:j.device,items:(await call('POST','/estimate/average-position-bid/id',{device:j.device,items:j.rows.map(x=>({key:x.id,position:3}))})).estimate}));if(est.some(x=>!Array.isArray(x.items)))throw Error('estimates');save('delivery_estimates3',est);
const em=new Map();for(const b of est)for(const e of b.items){const x=em.get(e.nccKeywordId)||{};x[b.device]=e.bid;em.set(e.nccKeywordId,x);}
const plan=choices.map(x=>{const e=em.get(x.id)||{},need=x.pcWeight>0&&x.moWeight>0?Math.ceil(Math.max((e.PC||0)*100/x.pcWeight,(e.MOBILE||0)*100/x.moWeight)*1.1/10)*10:null;return{...x,estimatedPC3:e.PC??null,estimatedMO3:e.MOBILE??null,estimatedRequiredBid:need,proposedBid:need?Math.max(x.bid,Math.min(30000,need)):x.bid,reason:!x.usable?'송출불가_상태확인':need>x.bid?'3위추정가미달':'현재입찰유지',estimateIsActualRank:false};});save('delivery_plan',plan);
console.log('PLAN',JSON.stringify({keywords:plan.length,unusable:plan.filter(x=>!x.usable).map(x=>({keyword:x.keyword,ks:x.keywordStatus,gs:x.groupStatus,cs:x.campaignStatus,ads:x.servingAds,lock:x.keywordLock})),raises:plan.filter(x=>x.proposedBid>x.bid).length,overCap:plan.filter(x=>x.estimatedRequiredBid>Math.max(30000,x.bid)).length,topRaises:plan.filter(x=>x.proposedBid>x.bid).sort((a,b)=>b.proposedBid-a.proposedBid).slice(0,20).map(x=>({keyword:x.keyword,from:x.bid,to:x.proposedBid,need:x.estimatedRequiredBid}))}));
})().catch(e=>{save('delivery_error',{error:String(e)});console.error(e);process.exitCode=1;});
