const fs=require('fs'),path=require('path');const {req,pool}=require('./_sojam_naver');const {evaluate}=require('./_kiness_review_rubric');const {policy}=require('./_kiness_20260909_policy');
const D=path.join(__dirname,'reports/kiness_delivery_boost_20260909');fs.mkdirSync(D,{recursive:true});const save=(n,v)=>fs.writeFileSync(path.join(D,n+'.json'),JSON.stringify(v));const call=async(p)=>{const r=await req('GET',p,null,441986,4);if(r===undefined)throw Error('Missing '+p);return r;};
(async()=>{
 const camps=await call('/ncc/campaigns');save('campaigns_live',camps);const cm=new Map(camps.map(c=>[c.nccCampaignId,c]));
 const batches=await pool(camps,6,c=>call('/ncc/adgroups?nccCampaignId='+c.nccCampaignId));if(batches.some(x=>!Array.isArray(x)))throw Error('Incomplete groups');const groups=batches.flat();save('groups_before',groups);
 const active=groups.filter(g=>!g.userLock&&!cm.get(g.nccCampaignId).userLock&&g.adgroupType==='WEB_SITE');console.log('active groups',active.length);
 const inv=await pool(active,6,async g=>({gid:g.nccAdgroupId,keywords:await call('/ncc/keywords?nccAdgroupId='+g.nccAdgroupId)}));if(inv.some(x=>!Array.isArray(x.keywords)))throw Error('Incomplete inventory');save('inventory_before',inv);
 const gm=new Map(groups.map(g=>[g.nccAdgroupId,g])),legacy=new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'_kiness_pc5_targets.json'),'utf8')).map(x=>x.id)),rows=[];
 for(const x of inv){const g=gm.get(x.gid),c=cm.get(g.nccCampaignId);for(const k of x.keywords){if(k.userLock||k.status!=='ELIGIBLE')continue;const e=evaluate(k.keyword),p=policy(k.keyword,e,legacy.has(k.nccKeywordId));if(p.protected5||['A','B','C'].includes(e.category)||p.tier.startsWith('D1'))rows.push({id:k.nccKeywordId,gid:x.gid,cid:g.nccCampaignId,keyword:k.keyword,campaign:c.name,group:g.name,category:e.category,tier:p.tier,protected5:p.protected5,oldBid:k.bidAmt,oldGroupBid:k.useGroupBidAmt,oldBase:k.useGroupBidAmt?g.bidAmt:k.bidAmt,pcWeight:g.pcNetworkBidWeight??100,mobileWeight:g.mobileNetworkBidWeight??100,status:k.status,statusReason:k.statusReason});}}
 save('targets',rows);console.log('high-intent targets',rows.length,'regional',rows.filter(x=>x.protected5).length);
 const ads=await pool([...new Set(rows.map(x=>x.gid))],6,async gid=>({gid,ads:await call('/ncc/ads?nccAdgroupId='+gid)}));if(ads.some(x=>!Array.isArray(x.ads)))throw Error('Incomplete ads');save('ads',ads);
 const targetBatches=[];for(let i=0;i<active.length;i+=20)targetBatches.push(active.slice(i,i+20));const ts=await pool(targetBatches,4,x=>call('/ncc/targets?ownerIds='+encodeURIComponent(x.map(g=>g.nccAdgroupId).join(','))));if(ts.some(x=>!Array.isArray(x)))throw Error('Incomplete targeting');save('targeting',ts.flat());
 for(const [name,since,until]of [['today','2026-09-09','2026-09-09'],['week','2026-09-02','2026-09-08']]){const data=[];for(let i=0;i<camps.length;i+=50){const r=await call('/stats?ids='+encodeURIComponent(camps.slice(i,i+50).map(c=>c.nccCampaignId).join(','))+'&fields='+encodeURIComponent(JSON.stringify(['salesAmt','clkCnt','impCnt']))+'&timeRange='+encodeURIComponent(JSON.stringify({since,until})));if(!Array.isArray(r.data))throw Error('Stats missing');data.push(r);}save('stats_'+name,data);console.log(name,data.flatMap(x=>x.data).reduce((a,x)=>({cost:a.cost+(x.salesAmt||0),clicks:a.clicks+(x.clkCnt||0),imps:a.imps+(x.impCnt||0)}),{cost:0,clicks:0,imps:0}));}
 save('collect_done',{at:new Date().toISOString(),activeGroups:active.length,targets:rows.length});
})().catch(e=>{save('collect_error',{at:new Date().toISOString(),error:String(e)});console.error(e);process.exitCode=1;});
