import json,html,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=ROOT/'reports/sojam-20260914/proposal-improvements/landing-preview';D.mkdir(parents=True,exist_ok=True)
C=json.loads((Path(__file__).parent/'clinic.json').read_text(encoding='utf8'))
CSS='''*{box-sizing:border-box}body{margin:0;background:#f7f6f1;color:#203b36;font-family:"Malgun Gothic",sans-serif;line-height:1.8}a{color:inherit}header,main,footer{max-width:1000px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #d8dfd7}.brand{font-size:22px;font-weight:800;text-decoration:none}.tag{color:#587164;font-size:14px}h1{font-size:clamp(32px,5vw,54px);line-height:1.35;letter-spacing:-2px;margin:18px 0 24px;max-width:790px}h2{font-size:27px;letter-spacing:-1px;margin-top:0}h3{font-size:18px}.hero{padding:62px 0 40px}.lead{font-size:20px;max-width:680px;color:#486457}.pills{display:flex;gap:10px;flex-wrap:wrap}.pill{border:1px solid #bdcbbf;border-radius:24px;padding:5px 14px;font-size:14px}.buttons{display:flex;flex-wrap:wrap;gap:12px;margin:28px 0}.button{background:#244d40;color:white;padding:14px 22px;border-radius:10px;font-weight:bold;text-decoration:none;display:inline-block}.secondary{background:white;color:#244d40;border:1px solid #c0cfc4}.note{font-size:14px;color:#576d61}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card,section.block{background:white;border:1px solid #dce3db;padding:28px;border-radius:18px;margin:18px 0}.grid .card{margin:0}.step{display:grid;grid-template-columns:45px 1fr;gap:12px;padding:16px 0;border-bottom:1px solid #e5e9e3}.step:last-child{border-bottom:0}.num{color:#789a6b;font-size:26px}.step h3,.step p{margin:0}details{padding:16px 0;border-bottom:1px solid #e2e6df}summary{cursor:pointer;font-weight:bold}footer{font-size:13px;color:#60766b;padding-bottom:110px}.fixed{position:fixed;bottom:0;left:0;right:0;background:#f7f6f1ee;border-top:1px solid #dce3db;padding:10px 20px;display:flex;justify-content:center;gap:10px}.fixed .button{margin:0;padding:10px 20px}.review{background:#e9eedf;font-size:13px;text-align:center;padding:9px 18px}ul{padding-left:22px}a:focus-visible,summary:focus-visible{outline:3px solid #a67829;outline-offset:4px}@media(max-width:620px){.grid{grid-template-columns:1fr}header,main,footer{padding:20px}.hero{padding:32px 0}h1{letter-spacing:-1px}.lead{font-size:17px}.card,section.block{padding:22px}.tag{font-size:12px}header .tag{max-width:140px;text-align:right}.fixed .button{font-size:14px;padding:10px 12px}.buttons .button{flex:1;text-align:center;padding:12px 10px}}@media print{.fixed,.review{display:none}body{background:white}.card,section.block{break-inside:avoid}}'''
def esc(x):return html.escape(str(x),quote=True)
def buttons():return f'<div class="buttons"><a class="button" data-contact="kakao" href="{esc(C["kakao_url"])}" target="_blank" rel="noopener noreferrer">초진 일정·비용 문의</a><a class="button secondary" data-contact="phone" href="tel:025985358">전화로 예약 문의</a></div>'
pages=[('p01','성인 아토피','반복되는 아토피 증상,<br>현재 상태와 치료 계획을<br>차근히 상담하세요.','가려움과 피부 변화가 일상에 어떤 영향을 주는지, 이전 진료와 사용 중인 약은 무엇인지 함께 확인합니다.','현재 증상과 지속 기간, 기존 진단과 사용 중인 약을 알려주세요. 수면·업무·생활에서 어려운 점도 진료에 참고할 수 있습니다.'),('p02','습진·한포진','손발의 반복되는 불편함,<br>진료 과정과 관리 계획부터<br>알아보세요.','반복되는 피부 변화와 일상생활의 불편을 듣고, 진료 후 상태와 생활 여건에 맞는 관리 계획을 설명합니다.','손발 피부 변화가 언제부터 시작됐는지, 업무 중 물·세제·장갑 등 접촉 환경과 이전 치료 내용을 정리해 주세요. 증상만으로 질환을 확정하지 않습니다.')]
for code,disease,headline,lead,prepare in pages:
    cost=esc(C['first_visit_cost'])if C['first_visit_cost']is not None else '초진 비용은 예약 문의 시 확인해 주세요.'
    hours=esc(C['hours_display'])if C['hours_confirmed']and C['hours_display']else '진료일과 가능한 초진 시간은 예약 문의 시 확인해 주세요.'
    body=f'''<div class="review">검토용 시안 · 현재 비용표·진료시간·개인정보 안내 확인 후 기존 홈페이지에 반영</div><header><a class="brand" href="https://www.sojam.co.kr/">소잠한의원</a><span class="tag">강남역 · {esc(disease)} 진료 안내</span></header><main><section class="hero"><div class="tag">첫 진료를 고민하고 계신 분께</div><h1>{headline}</h1><p class="lead">{lead}</p><div class="pills"><span class="pill">상태와 생활 여건 확인</span><span class="pill">비용·일정 먼저 문의</span><span class="pill">진료 후 치료 여부 결정</span></div>{buttons()}<p class="note">문의 버튼은 카카오 상담 채널로 연결됩니다. 문의만으로 예약이 확정되지는 않습니다.</p></section><div class="grid"><article class="card"><h2>첫 방문, 시간을<br>충분히 확보해 주세요</h2><p>공식 FAQ는 첫 상담에 약 2시간이 소요된다고 안내합니다. 현재 예약 시간과 예상 소요시간은 상담 시 다시 확인해 주세요.</p></article><article class="card"><h2>시작 전에<br>비용 구조를 확인하세요</h2><p>{cost}</p><p>한약·처치·외용제 등 포함 항목과 별도 비용, 예상 방문 빈도, 중단·환불 절차를 함께 문의해 주세요.</p></article></div><section class="block"><h2>처음 진료받기까지</h2><div class="step"><span class="num">01</span><div><h3>일정·비용 문의</h3><p>방문 가능한 날짜와 시간, 궁금한 비용 항목을 확인합니다.</p></div></div><div class="step"><span class="num">02</span><div><h3>현재 상태와 진료 이력 확인</h3><p>{prepare}</p></div></div><div class="step"><span class="num">03</span><div><h3>진료 후 계획 설명</h3><p>제안된 치료 항목, 예상 일정, 재평가 시점과 비용을 듣고 치료 시작 여부를 결정합니다. 경과와 필요한 기간은 개인별로 다를 수 있습니다.</p></div></div></section><section class="block"><h2>예약 전에 많이 묻는 질문</h2><details open><summary>기존에 쓰던 약은 어떻게 하나요?</summary><p>복용약과 바르는 약의 이름 또는 처방 내용을 준비해 주세요. 약 변경이나 중단은 담당 의료진과 상의해 결정하세요.</p></details><details><summary>3개월 결제와 치료기간은 같은 뜻인가요?</summary><p>결제 단위와 예상 관리기간, 재평가 시점은 서로 다른 항목입니다. 공식 FAQ의 약 120일 안내가 개인에게 그대로 적용되는 것은 아니므로 진료 후 계획을 확인해 주세요.</p></details><details><summary>멀리서 방문해도 괜찮을까요?</summary><p>이동시간뿐 아니라 이후 방문 빈도, 가능한 요일, 총 비용을 먼저 문의해 주세요. 반복 방문이 가능한지도 함께 검토하는 것이 좋습니다.</p></details><details><summary>예약을 변경하려면 어떻게 하나요?</summary><p>예약한 상담 채널이나 전화로 변경 가능 일정을 문의해 주세요. 변경이 확정됐는지 안내를 확인해 주세요.</p></details></section><section class="block"><h2>방문 준비와 위치</h2><ul><li>기존 진단·진료 내용과 사용 중인 약 목록</li><li>증상 시작 시기와 생활에서 불편한 점</li><li>비용·방문 빈도·재평가와 관련해 궁금한 질문</li></ul><p><strong>{esc(C['address'])}</strong><br>{hours}</p><p>주차·이동 지원이 필요하면 예약 문의 시 말씀해 주세요.</p>{buttons()}</section></main><footer>소잠한의원 · 대표 안경모 · {esc(C['phone'])}<br>{esc(C['address'])}<br>진료 안내는 일반적인 과정 설명이며 개인의 진단이나 치료 결과를 보장하지 않습니다.<br><a href="https://www.sojam.co.kr/49">공식 FAQ</a> · <a href="https://www.sojam.co.kr/57">의료진 소개</a></footer><div class="fixed"><a class="button" data-contact="kakao" href="{esc(C['kakao_url'])}" target="_blank" rel="noopener noreferrer">초진 일정·비용 문의</a><a class="button secondary" data-contact="phone" href="tel:025985358">전화 문의</a></div>'''
    doc=f'<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{esc(disease)} 첫 진료·비용 안내 | 소잠한의원</title><meta name="description" content="{esc(disease)} 진료를 고민하는 분을 위한 소잠한의원 초진 과정, 비용 확인 항목, 방문 준비 안내."><style>{CSS}</style></head><body data-page-code="{code}">{body}<script src="measurement.js"></script></body></html>'
    (D/(code+'.html')).write_text(doc,encoding='utf8')
shutil.copyfile(Path(__file__).parent/'measurement.js',D/'measurement.js')
(D/'index.html').write_text('<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>소잠 랜딩 검토</title><body style="font-family:sans-serif;padding:40px"><h1>소잠 질환별 진료 안내 시안</h1><p>비용표·운영정보 확인과 의료진 검토 후 반영할 시안입니다.</p><p><a href="p01.html">성인 아토피</a></p><p><a href="p02.html">습진·한포진</a></p></body></html>',encoding='utf8')
print('Built p01.html, p02.html, measurement.js')
